#!/usr/bin/env python3
"""Render frozen implementation 84 performance observations."""
from pathlib import Path
import json,statistics
R=Path(__file__).resolve().parents[2];p=json.loads((R/'student.tests/pa18/loop84-performance.json').read_text());assert p.get('finished_utc')
lines=['# PA18 implementation 84 performance evidence','',
 'Acceptance is **PA18/O0 LowIR**, spec §9. The [frozen harness](../student.tests/pa18/benchmark84.py) records source text/hashes, binary hashes, flags, CPU, warmups, telemetry and every sample in [the final observations](../student.tests/pa18/loop84-performance.json). [The initial observations](../student.tests/pa18/loop84-performance-initial.json) remain intact. Both use entry `09a77fca` and implementation `b4d66361` (measured repository tip `7a7ce959`, whose additional changes are proved oracles).','',
 'Each comparable workload has one warmup per binary, four A/A calibration samples and four ABBA blocks. Rejected/incorrect baseline behavior receives six final-only samples. Compiler wall time and peak RSS use a separate `/usr/bin/time` invocation. Native construction, correctness preflight and runtime timing are separate. Runtime inputs use volatile bounds and checked data-dependent sums; the empty-aggregate loop executes 24 million calls and the delegation loop executes 12 million calls.','',
 'Build flags are `g++ -std=gnu++11 -Wall -O3`; compiler flags are `--emit-lowir -O0`. Separate preflights use `--stats --validate-lowir`. Executables use the supplied `lowir2native-ref -O0`, bundle `c2f713cd70d06170632bfde3e75dd6fe1aa44d98`. Each emitted executable is checked before cost comparison. Own native optimization, debug and self-hosting remain later-stage work.','',
 'The initial run overlapped independent correctness validation and contains large compiler timing outliers (paired ranges include 0.656–0.987 for ordering-2400 and 0.773–1.005 for the common corpus). No compiler speedup is claimed from those values. The complete second run started after validation finished; neither run discards observations. The second run still shows large wall-time variation: several unchanged workloads take roughly twice the first-run time, and the 2400-function empty-aggregate paired range is 0.557–1.061. Neither set supports precise compiler speedup claims; instruction/work counts provide the complexity evidence. Both show the same substantial empty-helper runtime improvement.','',
 '## Compiler latency, RSS and executable size','',
 'Times are median milliseconds; ratio is median of paired block B/A means, with the full paired range. RSS is maximum observed KiB. Executable size is the sectionless ELF payload, including static data, **not isolated `.text`**; compiler size below is actual `.text`. Small source timings are startup-limited diagnostics.','',
 '| Workload | A / B ms | B/A (range) | A / B KiB | A / B native payload bytes |',
 '|---|---:|---:|---:|---:|']
for name,v in p['workloads'].items():
 c=v['compiler'];a=c.get('0');b=c['1'];ratios=c.get('paired_b_over_a',[])
 ratio=f"{statistics.median(ratios):.3f} ({min(ratios):.3f}–{max(ratios):.3f})" if ratios else 'final only'
 time=f"{a['median_wall_s']*1000:.2f} / {b['median_wall_s']*1000:.2f}" if a else f"— / {b['median_wall_s']*1000:.2f}"
 rss=f"{a['peak_rss_kib']} / {b['peak_rss_kib']}" if a else f"— / {b['peak_rss_kib']}"
 outs={x['binary']:x for x in v['outputs']};sizes=' / '.join(str(outs[i]['native']['payload_bytes']) if i in outs and 'native'in outs[i] else '—' for i in (0,1))
 lines.append(f'| {name} | {time} | {ratio} | {rss} | {sizes} |')
lines+=['',f"Startup medians: **{p['startup']['0']['median_wall_s']*1000:.2f} / {p['startup']['1']['median_wall_s']*1000:.2f} ms**.",'','## Executable runtime','',
 '| Workload | A / B ms | B/A (range) | A / B payload bytes |','|---|---:|---:|---:|']
for name,v in p['workloads'].items():
 if 'runtime'not in v:continue
 c=v['runtime'];r=c['paired_b_over_a'];sizes=[x['native']['payload_bytes']for x in v['outputs']]
 lines.append(f"| {name} | {c['0']['median_wall_s']*1000:.2f} / {c['1']['median_wall_s']*1000:.2f} | {statistics.median(r):.3f} ({min(r):.3f}–{max(r):.3f}) | {sizes[0]} / {sizes[1]} |")
a,b=[x['text_bytes']for x in p['binaries']]
lines+=['',f'Compiler `.text`: **{a:,} → {b:,} bytes**, **+{b-a:,} ({(b/a-1)*100:.3f}%)**.','',
 '## Work bounds and acceptance','',
 'The delegated-entry queue uses canonical entity IDs and an O(1)-average flat index. Every base/complete/polymorphic bit crosses its selected edge once at most. Scratch is released after semantic completion. There is one final pass over demanded members; insertion does not retry unrelated classes, candidates or bodies. For 150 → 600 specializations, measured delegation-entry work is **300 → 1200**, semantic entities **2111 → 8411**, and LowIR instructions **3313 → 13213**. Both binaries emit the same instruction counts in this family. No grammar replay, global invalidation or semantic reconstruction is introduced.','',
 'Empty aggregate helper omission checks only the group head and removes a no-effect call/body before either is emitted. Its work bound is **one O(1) check per group**, with **zero allowed code growth** and the ordinary action path as fallback. Empty classes with a declared destructor or transfer, or a volatile source, use ordinary checked transfers; that necessary work is not optional. One explicit widening instruction per affected operand preserves the required O0 conversion boundary. No optimizer pass or speculative code growth is added. Existing initializer expansion and named-result summary limits remain unchanged.','',
 'The empty-helper runtime workload drops from 224 to 201 payload bytes, removing one empty helper body and its call. It preserves the live destination, argument call and data-dependent work. The repeatable runtime improvement, smaller output and reduced compiler work justify this local omission. The initial run had a paired runtime median of **0.709** (range **0.704–0.711**); the final table supplies independent confirmation.','',
 'Unchanged ordering/common/call/memory/floating workloads retain exact LowIR; unchanged runtime probes retain identical executable bytes. Delegation runtime retains 256 payload bytes. The final identical-code runtime ratios are 0.946, 1.011 and 1.022 for calls, memory and floating work, with ranges spanning both directions; their initial ratios were 1.002, 1.000 and 1.001. These inconsistent shifts on identical bytes disclose timing variation rather than evidence of a generated-code improvement or regression. `empty-lifetime-600` is final-only because entry emits invalid by-value argument LowIR for an empty class with a nontrivial destructor. Its final executable checks two demanded calls and all four destructor effects; the rejected entry cannot be a fast correctness baseline.','',
 'PA18/O0 mandates no numeric compiler-latency or RSS ceiling. Historical +15%, +16 MiB and 5.5× targets remain diagnostic, with earlier measurements preserved. Correctness, unchanged coverage, bounded work and optional-transform profitability remain mandatory. Necessary ABI/value checks receive measured costs; later native optimization is not an additional PA18 exit gate. There is no avoidable regression established by these observations.','']
(R/'pa18/performance84.md').write_text('\n'.join(lines))
