#pragma once
#include "semantic/analyzer.h"
#include "lowir/model.h"
#include "abi/itanium/graph.h"
#include <memory>
namespace cppgm { namespace lowering {
using semantic::EntityId;
using semantic::TypeId;
using semantic::NodeId;
using semantic::SourceInvocationScope;
using semantic::TypeKind;
using semantic::ValueCategory;
using lowir_model::Operand;
using lowir_model::Instruction;
using lowir_model::Opcode;
using lowir_model::Operation;
using lowir_model::SymbolId;
using lowir_model::SlotId;
using lowir_model::BlockId;
using lowir_model::FunctionId;
using lowir_model::SignatureId;
using IRType = lowir_model::Type;
struct Value {
    Operand operand;
    IRType ir;
    TypeId type = 0, normalized_integer = 0;
    EntityId bit_field = 0, parameter_object = 0;
    std::uint64_t init_offset = 0;
    bool address = false, cached = false, nonnull = false, member_zero_adjustment = false;
    bool initializing = false, overlapping = false;
    Operand stored;
    SlotId materialized;
    Value() {}
    Value(Operand o, IRType i, TypeId t = 0, bool a = false) : operand(o), ir(i), type(t), address(a) {}
};
// Program-owned linkage identities survive individual semantic TUs. Keys use
// canonical typed ABI entities, never their rendered manglings.
struct Linkage {
    semantic::Index construction_symbols, member_thunk_symbols;
    struct ValueBaseArgument { unsigned parameter; std::uint64_t offset; };
    struct ParameterAbi { unsigned visible; lowir_model::Range hidden; };
    std::vector<ValueBaseArgument> value_base_arguments;
    std::vector<ParameterAbi> parameter_abis = std::vector<ParameterAbi>(1);
    semantic::Index signature_parameter_abis;
    abi_mangle::Graph abi;
    semantic::Index external, native_names, incomplete_signatures;
    semantic::Index view_symbols, thunk_adjustments, thunk_result_pairs, thunk_pairs, thunk_symbols;
    unsigned next_thunk_adjustment = 0, next_thunk_result = 0, next_thunk_pair = 0;
    std::size_t requests = 0, hits = 0;
    std::uint64_t disambiguator = 0;
    bool merge, presentation;
    bool host = false;
    SymbolId allocation_roles[2], rtti_roles[9], rtti_functions[3];
    SymbolId exception_functions[8];
    SymbolId atomic_runtime_symbols[4];
    SymbolId complex_runtime_symbols[6];
    SymbolId terminate_adapter;
    SymbolId abort_runtime;
    std::vector<FunctionId> initializers, finalizers;
    void finish_lifecycle(lowir_model::Program& program);
    explicit Linkage(bool merge, bool presentation = false) : merge(merge), presentation(presentation) {}
};
// The semantic TU outlives this adapter; all mappings are dense canonical IDs.
// Function-local construction state is discarded when its body is complete.
class Procedural {
    semantic::SourceInvocation source_invocation;
    semantic::Index source_string_symbols;
    struct SourceString { IdentifierId text; SymbolId symbol; };
    std::vector<SourceString> source_strings;
    SymbolId source_string_symbol(IdentifierId text);
    void emit_source_strings();
    syntax::AstView ast;
    semantic::Analyzer& sem;
    IdentifierTable& identifiers;
    lowir_model::Program& p;
    Linkage& linkage;
    abi_mangle::Graph& abi;
    std::vector<abi_mangle::Id> abi_types, abi_scopes;
    semantic::Index abi_support_symbols;
    std::vector<unsigned char> internal_scopes, internal_entities, local_abi_scopes, local_abi_types;
    std::vector<SymbolId> symbols, strings, base_symbols;
    std::vector<SlotId> objects;
    std::vector<lowir_model::ValueId> object_addresses;
    semantic::Index string_index;
    semantic::Index constant_arrays;
    semantic::Index constant_data_index;
    struct ConstantDataRecord { lowir_model::Range data; std::uint64_t bytes, alignment; SymbolId symbol; std::uint32_t next; };
    std::vector<ConstantDataRecord> constant_data_records = std::vector<ConstantDataRecord>(1);
    void initialize_constant_array(EntityId e, Value location, semantic::Constant value = semantic::Constant());
    void initialize_context_reference(const semantic::Analyzer::ContextReference& plan, Value location);
    struct StringRecord { NodeId node; std::uint32_t next; };
    std::vector<StringRecord> string_records = std::vector<StringRecord>(1);
    std::vector<BlockId> labels;
    std::vector<unsigned char> control_entries;
    std::vector<SignatureId> indirect_signatures;
    std::vector<Operand> call_work;
    std::vector<EntityId> definitions, global_initializers;
    struct LocalStatic { EntityId object; SymbolId guard, destructor; bool dynamic; };
    std::vector<LocalStatic> local_statics = std::vector<LocalStatic>(1);
    semantic::Index local_static_index, local_static_references;
    semantic::Index reference_ordinals;
    struct LocalStaticReference { EntityId object; std::uint32_t next; };
    std::vector<LocalStaticReference> local_static_reference_objects = std::vector<LocalStaticReference>(1);
    SymbolId atexit_symbol;
    void prepare_local_static(EntityId e, bool dynamic);
    void initialize_local_static(EntityId e);
    void register_inline_temporaries(EntityId e);
    void emit_local_static_destructors();
    struct AllocationAdapter { SymbolId symbol, runtime; };
    std::vector<AllocationAdapter> allocation_adapters;
    void emit_allocation_adapters();
    struct TlsInitializer { EntityId object; SymbolId guard, initializer, wrapper; };
    std::vector<TlsInitializer> tls_initializers;
    semantic::Index tls_wrappers;
    EntityId active_tls = 0;
    void prepare_tls(EntityId object);
    void emit_tls_initializers();
    std::unique_ptr<lowir_model::FunctionBuilder> builder;
    FunctionId function;
    TypeId returned = 0;
    Value return_destination;
    IRType result_type() const;
    void finish_exception_boundary();
    void emit_terminate_adapter();
    void construct_value(NodeId n, const semantic::Conversion& conversion, Value destination, bool terminal = false, bool base = false, bool entry = false);
    Value list_conversion(const semantic::Conversion& conversion, Value destination = Value());
    Value class_temporary(EntityId object, TypeId type);
    Value class_address(EntityId object, TypeId type);
    SlotId this_slot;
    unsigned initializer_receiver = 0;
    Value implicit_object();
    void transfer_body(EntityId e);
    void transfer_action(const semantic::TransferAction& action, Value source, Value target, bool assignment);
    void inherited_call(EntityId e, Value object);
    void transfer_array(const semantic::TransferAction& action, Value source, Value target, bool assignment, bool member_root = false);
    BlockId break_target, continue_target;
    bool ended = false;
    std::uint32_t live = 0;
    bool emitting_cleanup = false, resume_emitted = false;
    EntityId returning_object = 0;
    semantic::Index return_unwind_states;
    std::uint32_t return_unwind_state();
    bool deallocation_boundary = false;
    std::size_t cleanup_cursor = 0;
    semantic::Index slot_names;
    SlotId cleanup_return;
    SlotId class_return_slot;
    BlockId resume_terminal, destructor_handler, destructor_end, destructor_epilogue;
    semantic::Index cleanup_index, return_terminals;
    struct Cleanup { std::uint32_t state; BlockId next, block; };
    std::vector<Cleanup> cleanup_blocks;
    struct TemporaryState : semantic::LifetimeState { lowir_model::ValueId location; SlotId selector, constructed, saved_location; std::uint32_t yes = 0, no = 0, release = 0; TypeId destroyed_type = 0; };
    struct ReleaseAction { SymbolId function; std::uint32_t begin, count; };
    struct ReleaseOperand { SlotId slot; IRType type; };
    std::vector<ReleaseAction> release_actions;
    std::vector<ReleaseOperand> release_operands;
    std::uint32_t protect_deallocation(EntityId function, const Operand* operands, unsigned count);
    std::uint32_t protect_exception(Operand object);
    void release_allocation(std::uint32_t action);
    void retire_deallocation(std::uint32_t state, std::uint32_t initial);
    void activate_subobject(TypeId type, Value address, SlotId count, semantic::Index& retired);
    void complete_subobject(TypeId type, Value address, std::uint32_t before, bool retain, bool defaults, semantic::Index& retired);
    std::vector<TemporaryState> temporary_states;
    semantic::Index list_backing_addresses;
    std::vector<lowir_model::ValueId> list_element_addresses;
    struct ExceptionContext { std::uint32_t parent = 0, live = 0; NodeId node = 0; BlockId entry; bool handler = false, has_catches = false, cleanup_dispatch = false; };
    std::vector<ExceptionContext> exception_contexts = std::vector<ExceptionContext>(1);
    std::uint32_t exception_context = 0, nonthrowing_parameters = 0;
    semantic::Index exception_rtti, exception_storage, exception_selectors;
    unsigned exception_selector_count = 0;
    enum class UnwindKind { TryExit, HandlerExit, Dispatch };
    struct UnwindContinuation { UnwindKind kind; std::uint32_t context; BlockId block, next; bool pop; };
    std::vector<UnwindContinuation> unwind_continuations;
    std::size_t unwind_cursor = 0;
    semantic::Index unwind_terminals, unwind_dispatches;
    BlockId unwind_suffix(std::uint32_t state, std::uint32_t context, bool pop = true);
    BlockId unwind_target();
    bool unwind_live() const;
    void flush_unwind_continuations();
    void resume_exception(std::uint32_t state, std::uint32_t context, bool pop);
    SymbolId exception_function(unsigned role);
    SymbolId exception_type(TypeId type);
    std::string support_type_name(TypeId type);
    void exception_object(TypeId type);
    bool exception_clauses(std::uint32_t context, bool cleanup = false);
    unsigned exception_selector(NodeId handler);
    ir_model::CatchBinding catch_binding(NodeId handler) const;
    Value begin_catch(Operand object, NodeId handler = 0);
    void try_statement(NodeId n);
    Value throw_expression(NodeId n);
    void exit_exception_contexts(NodeId target = 0, std::uint32_t stop = 0);
    void exception_fallback();
    std::vector<unsigned char> cleanup_expressions;
    bool cleanup_expression(NodeId n, bool omit_result = false, bool effects_only = false);
    const semantic::Expression* conversion_call(const semantic::Conversion& conversion) const;
    std::vector<unsigned char> unwind_expressions;
    std::vector<unsigned char> proven_unwind_expressions;
    bool unwind_expression(NodeId n, bool body_proof = false);
    struct FullExpression { NodeId root = 0, terminal_value = 0; bool enabled = false, open = false, lexical = false, terminal_branch = false, suppress_guard = false;
        EntityId result_temporary = 0;
        bool argument_storage = false, storage_boundary = false;
        bool scalar_terminal = false, scalar_unreachable = false, proven_nonthrowing = false; } full_expression;
    void begin_full_expression(NodeId n, bool omit_result = false);
    void finish_full_expression(std::uint32_t stop);
    void closure_adapter(EntityId e);
    void initialize_closure(NodeId n, Value destination);
    std::uint32_t retire_construction(std::uint32_t state, std::uint32_t stop, const semantic::Index& retired, semantic::Index& cache, std::uint32_t replacement = 0);
    Value captured_address(unsigned capture);
    void guard_expression(NodeId n, bool storage_ready = false);
    void open_expression_region();
    void close_expression_region();
    SlotId cleanup_selector(Value test, bool required);
    void merge_temporaries(std::uint32_t common, std::uint32_t yes, std::uint32_t no, SlotId selector);
    void destroy_lifetime(std::uint32_t state);
    semantic::LifetimeState lifetime_state(std::uint32_t state) const;
    void activate_temporary(EntityId e);
    semantic::Index reference_guards;
    semantic::Index local_reference_guards;
    void prepare_reference_guards(EntityId e);
    void destroy_reference_choices(EntityId e);
    void reference_global(EntityId e);
    void initialize_reference(EntityId e, Value location);
    SymbolId abort_symbol;
    Value abort_call();
    struct Constructed { semantic::SubobjectAction action; BlockId handler; };
    std::vector<Constructed> constructed_subobjects;
    std::uint32_t constructor_block_boundary = 0;
    EntityId active_function = 0;
    NodeId child(NodeId n, syntax::Kind k) const;
    std::string spelling(IdentifierId id) const;
    abi_mangle::Id abi_type(TypeId t);
    abi_mangle::Id abi_template_head(EntityId entity);
    abi_mangle::Id abi_tagged_name(EntityId, abi_mangle::Id);
    abi_mangle::Id abi_query(semantic::QueryId q);
    abi_mangle::Id abi_argument(semantic::ArgumentId argument);
    semantic::Index abi_queries;
    abi_mangle::Id abi_function_context(EntityId e);
    abi_mangle::Id abi_entity_name(EntityId e);
    abi_mangle::Id abi_template_type(abi_mangle::Id name, const std::vector<abi_mangle::Id>& arguments);
    void template_function_abi(EntityId e, abi_mangle::Function& target);
    void local_member_abi(EntityId e, abi_mangle::Function& target);
    bool internal_scope(semantic::ScopeId s);
    bool internal_entity(EntityId entity);
    bool local_abi_argument(semantic::ArgumentId argument);
    bool local_abi_scope(semantic::ScopeId s);
    bool local_abi_type(TypeId t);
    abi_mangle::Id abi_scope(semantic::ScopeId s);
    SymbolId symbol(EntityId e, bool base = false, bool deleting = false);
    bool separate_base(EntityId e) const;
    bool base_only_entry(EntityId e) const;
    abi_mangle::AbiTerminalKind operator_terminal(EntityId id) const;
    SymbolId fresh_symbol(const std::string& preferred);
    SignatureId signature(TypeId t, FunctionId owner = FunctionId());
    SignatureId function_signature(EntityId e, FunctionId owner, bool base = false);
    void lifecycle_arguments(EntityId target, std::vector<Operand>& args, unsigned base);
    Value lifecycle_address(EntityId base);
    Value lifecycle_vtt(unsigned index);
    bool active_base_entry = false;
    unsigned construction_base = 0;
    Value vtt_argument;
    semantic::Index hidden_base_addresses, parameter_base_addresses;
    void emit_construction_tables(EntityId cls, SymbolId table);
    void declare_function(EntityId e);
    void function_body(EntityId e, bool base = false);
    void reset_lifetime(EntityId e);
    void destroy(EntityId destructor, TypeId t, Value object);
    void destroy_object(EntityId object, EntityId destructor);
    void destroy_subobject(const semantic::DestructionAction& action);
    void clean_inline(std::uint32_t state, std::uint32_t stop);
    BlockId cleanup_suffix(std::uint32_t state, BlockId terminal, std::uint32_t stop = 0);
    void emit_cleanups();
    void flush_cleanups();
    SlotId source_slot(EntityId e);
    Value guarded_call(Instruction i, const Operand* args, std::size_t count);
    void return_statement(NodeId n);
    void destructor_prologue(EntityId e);
    void destructor_finish(EntityId e, bool returning = true);
    void destroy_subobjects(EntityId e);
    void finish_constructor_handlers();
    void constructor_cleanup(semantic::SubobjectAction action);
    void finish_subobject(semantic::SubobjectAction action);
    semantic::Index initialized_units;
    unsigned initialization_expansion = 1;
    struct InitProjection { std::uint64_t offset; bool field; EntityId entity; TypeId element = 0;
        InitProjection(std::uint64_t o, bool f, EntityId e = 0) : offset(o), field(f), entity(e) {} };
    Value array_element(Value root, bool indirect, const std::vector<InitProjection>& path, Operand index, std::uint64_t stride);
    void array_construct(EntityId ctor, TypeId t, Value root, bool indirect, const std::vector<InitProjection>& path);
    void array_destroy(EntityId dtor, TypeId t, Value root, bool indirect, const std::vector<InitProjection>& path, bool subobject = false);
    Value initialization_address(Value root, bool indirect, const std::vector<InitProjection>& path);
    struct AggregateHelper { TypeId type; FunctionId function; std::uint32_t actions, count; };
    semantic::Index aggregate_helpers, aggregate_array_parameters;
    std::vector<AggregateHelper> aggregate_definitions;
    std::vector<std::uint32_t> aggregate_actions;
    SymbolId aggregate_helper(std::uint32_t plan);
    bool array_parameter(TypeId type);
    bool call_aggregate_helper(std::uint32_t plan, Value location);
    void emit_aggregate_helpers();
    void initialize_plan(std::uint32_t plan, Value location);
    void initialize_array_copy(std::uint32_t plan, Value location, Value source);
    SlotId repeat_initializer(std::uint32_t plan, Value base, std::uint64_t count = 0, TypeId type = 0);
    void aggregate_plan(std::uint32_t plan, Value root, bool indirect, std::vector<InitProjection>& path, Value* initialized = nullptr);
    void global_plan(std::uint32_t plan);
    void global_bit_field(std::uint32_t plan, std::uint64_t& bytes);
    void global_bit_field_value(EntityId field, std::uint64_t offset, std::uint64_t value, std::uint64_t& bytes);
    void global_construction(NodeId n, TypeId t);
    void global_constant_fields(const semantic::ConstantObject& fields, TypeId t);
    Value constant_operand(semantic::Constant value, TypeId t);
    Operand integer_operand(semantic::Constant value);
    Value string_element(NodeId source, TypeId element, std::uint64_t index);
    void aggregate_initialize(NodeId n, TypeId t, Value root, bool indirect, std::vector<InitProjection>& path);
    void constructor_body(EntityId e, bool base);
    void construct(EntityId ctor, NodeId init, Value object, bool base = false, bool entry = false);
    void global_initialization();
    void global_finalization();
    void global(EntityId e);
    void string_literal(NodeId n);
    void emit_string_literals();
    void numeric_string_literal(NodeId n);
    void literal_arguments(NodeId n);
    semantic::Index numeric_strings;
    Value offsetof_expression(NodeId);
    void global_data(NodeId n, TypeId t);
    lowir_model::DataItem constant_data(NodeId n, TypeId t);
    IRType type(TypeId t);
    bool reference(TypeId t) const;
    Value emit(Instruction i, const Operand* args, std::size_t count);
    Value emit_raw(Instruction i, const Operand* args, std::size_t count);
    Value emit(Instruction i, const std::vector<Operand>& args);
    Value emit(Instruction i, std::initializer_list<Operand> args);
    Value emit(Opcode op, IRType t, std::initializer_list<Operand> args, Operation action = Operation::None);
    Value load(Value v);
    Value load_bit_field(Value v);
    Value store_bit_field(Value v, Value location, SlotId container = SlotId());
    Value initialization_value(NodeId n, TypeId t);
    Value address(Value v);
    Value normalize_bit_integer(Value value);
    Value convert(Value v, TypeId target, bool fold_widen = false, bool preserve_widen = false);
    Value coerce(Value v, IRType target, bool unsign = false, bool to_unsigned = false, bool fold_widen = false, bool preserve_widen = false);
    Value converted(NodeId n, const semantic::Conversion& c);
    Value converted_value(Value value, const semantic::Conversion& conversion);
    Value user_conversion(NodeId n, const semantic::Conversion& conversion, Value destination = Value(), bool truth = false);
    Value incoming(NodeId n);
    Value expression(NodeId n, bool location = false);
    Value statement_expression(NodeId n, Value destination = Value());
    struct LifetimeOverlay { NodeId region; std::uint32_t anchor, replacement, parent; };
    std::vector<LifetimeOverlay> lifetime_overlays = std::vector<LifetimeOverlay>(1);
    semantic::Index mapped_lifetimes;
    semantic::Index initialization_guards;
    std::uint32_t lifetime_overlay = 0;
    std::uint32_t map_lifetime(std::uint32_t state, std::uint32_t overlay);
    std::uint32_t object_lifetime(EntityId object);
    semantic::LifetimeUse lifetime_use(NodeId n);
    bool discarded_access(NodeId n);
    void discard(NodeId n, bool access = true);
    Value unary(NodeId n);
    Value binary(NodeId n, bool location);
    bool inline_atomic(TypeId type);
    void assembly_statement(NodeId);
    Value atomic_scalar(AtomicOp op, IRType raw, Operand object, Operand value, Operand expected, bool native);
    Value atomic_runtime(AtomicOp op, std::uint64_t bytes, Operand object, Operand value, Operand result = Operand());
    Operand atomic_buffer(Value value);
    IRType atomic_representation(TypeId type);
    Value atomic_bits(Value value, IRType raw);
    Value atomic_value(Value bits, TypeId type);
    void atomic_extract(Value bits, Operand destination, TypeId type);
    void atomic_padding(TypeId type, Value destination);
    Value atomic_update(Value location, Value rhs, ETokenType op, TypeId computation, bool postfix);
    Value atomic_call(NodeId n, Value destination = Value());
    Value intrinsic_call(NodeId n, semantic::Intrinsic intrinsic);
    Value complex_construct(TypeId type, Value real, Value imag);
    Value complex_component(Value value, unsigned part);
    Value complex_projection(NodeId n);
    Value complex_convert(Value value, TypeId type);
    Value complex_operation(ETokenType op, Value a, Value b, TypeId result);
    void complex_data(TypeId type, semantic::Constant value);
    Value conditional(NodeId n, bool location, Value destination = Value(), std::uint32_t branches = 0, bool terminal = false, const semantic::ScalarConsumption* consumption = nullptr);
    Value logical(NodeId n);
    Value fold(NodeId n, bool location, Value* callable = nullptr);
    Value fold_operation(const semantic::RangeOperation& op, Value left, Value right, Value* callable);
    Value arrow_object(NodeId n, std::uint32_t chain);
    Value call(NodeId n, Value destination = Value());
    Value floating_builtin(NodeId n);
    lowir_model::DataItem floating_data(IRType type, long double value, bool signaling);
    Value floating_literal(TypeId type, long double value, bool signaling);
    Value overflow_builtin(NodeId n, semantic::Intrinsic intrinsic);
    Value integer_builtin(NodeId n, semantic::Intrinsic intrinsic);
    Value placement_new(NodeId n);
    Value delete_expression(NodeId n);
    Value array_new(NodeId n, const semantic::PlacementNew& use);
    void heap_array_destroy(EntityId destructor, TypeId leaf, Value data, Operand count);
    Value operation(ETokenType op, Value a, Value b, TypeId result);
    Value binding(EntityId e);
    Value field(Value base, EntityId e, unsigned steps = 0, TypeId object = 0);
    Value base_projection(Value base, unsigned steps);
    Value pointer_projection(Value base, unsigned adjustment);
    std::vector<SymbolId> vtables, deleting_symbols;
    struct AdjustorThunk { EntityId target; std::int64_t adjustment, result_adjustment, result_virtual_row; SymbolId symbol; bool deleting; };
    std::vector<AdjustorThunk> adjustor_thunks;
    SymbolId view_symbol(EntityId cls, unsigned view);
    SymbolId virtual_target(const semantic::VirtualSlot& slot, bool deleting);
    void emit_adjustor_thunks();
    std::vector<EntityId> deleting_entries;
    SymbolId pure_virtual;
    void emit_vtables();
    SymbolId vtable_symbol(EntityId cls);
    SymbolId deleting_symbol(EntityId e);
    void emit_deleting_entries();
    void order_lifecycle_entries();
    SymbolId typeinfo(EntityId cls);
    SymbolId rtti_type(TypeId type);
    SymbolId rtti_runtime(unsigned role);
    SymbolId rtti_function(unsigned role);
    Value rtti_expression(NodeId n);
    void rtti_failure(unsigned role);
    semantic::Index rtti_symbols;
    semantic::Index rtti_internal_types, rtti_incomplete_types;
    bool internal_rtti_type(TypeId type);
    unsigned rtti_incomplete_flags(TypeId type);
    SymbolId abi_type_global(TypeId type, abi_mangle::TargetKind kind);
    SymbolId abi_global(EntityId cls, abi_mangle::TargetKind kind);
    void vpointer_store(EntityId cls);
    Value virtual_function(Value object, unsigned slot);
    SignatureId virtual_signature(EntityId e);
    std::vector<SignatureId> virtual_signatures;
    SymbolId member_function_symbol(EntityId member);
    void emit_member_thunks();
    struct MemberThunk { EntityId member; SymbolId symbol; unsigned slot; };
    std::vector<MemberThunk> member_thunks;
    Value member_pointer_value(EntityId member, TypeId type, std::int64_t adjustment = 0);
    Value member_pointer_conversion(Value value, const semantic::Conversion& conversion);
    void member_pointer_data(const semantic::StaticValue& value);
    Value truth_operand(Value value);
    Value member_pointer_object(const semantic::ObjectUse& use, Value* function = nullptr);
    void zero_object(TypeId type, Value object);
    void zero_plan(std::uint32_t plan, Value object, bool scalar_access = false);
    void zero_padding(Value object, std::uint64_t offset, std::uint64_t bytes, std::uint64_t alignment);
    Value store(Value v, Value location);
    void initialize(NodeId n, TypeId t, Value location);
    void initialize_scalar(const semantic::ScalarConsumption& consumption, Value location);
    void object(EntityId e);
    void statement(NodeId n);
    void range_statement(NodeId n);
    Value range_operation(const semantic::RangeOperation& operation, const std::vector<Value>& args, Value destination = Value());
    Value typed_conversion(Value value, const semantic::Conversion& conversion, Value destination = Value());
    void range_initialize(EntityId object, const semantic::RangeOperation& operation, const std::vector<EntityId>& args, std::uint32_t conversion);
    bool mark_control_entries(NodeId n);
    void condition(NodeId n, BlockId yes, BlockId no);
    void switch_statement(NodeId n);
    void collect_cases(NodeId n, std::vector<NodeId>& cases, NodeId& fallback);
    BlockId block();
    void start(BlockId b);
    void jump(BlockId b);
public:
    std::size_t virtual_cache_bytes() const {
        return (vtables.capacity()+deleting_symbols.capacity())*sizeof(SymbolId)
            + virtual_signatures.capacity()*sizeof(SignatureId) + deleting_entries.capacity()*sizeof(EntityId);
    }
    std::size_t deleting_entry_count() const { return deleting_entries.size(); }
    std::size_t local_static_count() const { return local_statics.size()-1; }
    std::size_t constant_data_count() const { return constant_data_records.size()-1; }
    std::size_t constant_data_work = 0, constant_data_hits = 0;
    std::size_t aggregate_array_work = 0, aggregate_array_hits = 0;
    std::size_t control_work = 0, discard_work = 0;
    std::size_t full_expression_work = 0, full_expression_regions = 0;
    std::size_t statement_regions = 0, lifetime_mapping_work = 0, lifetime_mapping_hits = 0;
    std::size_t rtti_work = 0, rtti_hits = 0;
    Procedural(syntax::Ast& a, semantic::Analyzer& s, IdentifierTable& ids, lowir_model::Program& out, Linkage& links);
    void run();
};
void build_program(lowir_model::Program&, const std::vector<std::string>&, bool stats, const std::vector<std::string>& includes, const std::vector<std::string>& macros, bool presentation = false, bool host = false);
int emit_lowir(const std::string& output, const std::vector<std::string>& inputs, bool stats, bool audit = false);
} }
