#pragma once
#include "semantic/analyzer.h"
#include "lowir/model.h"
#include "abi/itanium/graph.h"
#include <memory>
namespace cppgm { namespace lowering {
using semantic::EntityId;
using semantic::TypeId;
using semantic::NodeId;
using semantic::TypeKind;
using semantic::ValueCategory;
using lowir_model::Operand;
using lowir_model::Instruction;
using lowir_model::Opcode;
using lowir_model::Operation;
using lowir_model::SymbolId;
using lowir_model::SlotId;
using lowir_model::BlockId;
using lowir_model::FunctionId;
using lowir_model::SignatureId;
using IRType = lowir_model::Type;
struct Value {
    Operand operand;
    IRType ir;
    TypeId type = 0;
    EntityId bit_field = 0;
    std::uint64_t init_offset = 0;
    bool address = false, cached = false;
    bool initializing = false;
    Operand stored;
    Value() {}
    Value(Operand o, IRType i, TypeId t = 0, bool a = false) : operand(o), ir(i), type(t), address(a) {}
};
// Program-owned linkage identities survive individual semantic TUs. Keys use
// canonical typed ABI entities, never their rendered manglings.
struct Linkage {
    abi_mangle::Graph abi;
    semantic::Index external, native_names;
    std::size_t requests = 0, hits = 0;
    std::uint64_t disambiguator = 0;
    bool merge;
    explicit Linkage(bool merge) : merge(merge) {}
};
// The semantic TU outlives this adapter; all mappings are dense canonical IDs.
// Function-local construction state is discarded when its body is complete.
class Procedural {
    syntax::Ast& ast;
    semantic::Analyzer& sem;
    IdentifierTable& identifiers;
    lowir_model::Program& p;
    Linkage& linkage;
    abi_mangle::Graph& abi;
    std::vector<abi_mangle::Id> abi_types, abi_scopes;
    std::vector<SymbolId> symbols, strings, base_symbols;
    std::vector<SlotId> objects;
    std::vector<lowir_model::ValueId> object_addresses;
    semantic::Index string_index;
    struct StringRecord { NodeId node; std::uint32_t next; };
    std::vector<StringRecord> string_records = std::vector<StringRecord>(1);
    std::vector<BlockId> labels;
    std::vector<unsigned char> control_entries;
    std::vector<unsigned char> discard_accesses;
    std::vector<SignatureId> indirect_signatures;
    std::vector<Operand> call_work;
    std::vector<EntityId> definitions, global_initializers;
    struct TlsInitializer { EntityId object; SymbolId guard, initializer, wrapper; };
    std::vector<TlsInitializer> tls_initializers;
    semantic::Index tls_wrappers;
    EntityId active_tls = 0;
    void prepare_tls(EntityId object);
    void emit_tls_initializers();
    std::unique_ptr<lowir_model::FunctionBuilder> builder;
    FunctionId function;
    TypeId returned = 0;
    Value return_destination;
    IRType result_type() const;
    void construct_value(NodeId n, const semantic::Conversion& conversion, Value destination);
    Value class_temporary(EntityId object, TypeId type);
    Value class_address(EntityId object, TypeId type);
    SlotId this_slot;
    void transfer_body(EntityId e);
    void transfer_action(const semantic::TransferAction& action, Value source, Value target, bool assignment);
    void transfer_array(const semantic::TransferAction& action, Value source, Value target, bool assignment, bool member_root = false);
    BlockId break_target, continue_target;
    bool ended = false;
    std::uint32_t live = 0;
    bool emitting_cleanup = false, resume_emitted = false;
    std::size_t cleanup_cursor = 0;
    semantic::Index slot_names;
    SlotId cleanup_return;
    BlockId resume_terminal, destructor_handler, destructor_end, destructor_epilogue;
    semantic::Index cleanup_index, return_terminals;
    struct Cleanup { std::uint32_t state; BlockId next, block; };
    std::vector<Cleanup> cleanup_blocks;
    struct TemporaryState : semantic::LifetimeState { SlotId selector; std::uint32_t yes = 0, no = 0; };
    std::vector<TemporaryState> temporary_states;
    std::vector<unsigned char> cleanup_expressions;
    bool cleanup_expression(NodeId n);
    SlotId cleanup_selector(Value test, bool required);
    void merge_temporaries(std::uint32_t common, std::uint32_t yes, std::uint32_t no, SlotId selector);
    void destroy_lifetime(std::uint32_t state);
    semantic::LifetimeState lifetime_state(std::uint32_t state) const;
    void activate_temporary(EntityId e);
    struct Constructed { semantic::SubobjectAction action; BlockId handler; };
    std::vector<Constructed> constructed_subobjects;
    EntityId active_function = 0;
    NodeId child(NodeId n, syntax::Kind k) const;
    std::string spelling(IdentifierId id) const;
    abi_mangle::Id abi_type(TypeId t);
    abi_mangle::Id abi_scope(semantic::ScopeId s);
    SymbolId symbol(EntityId e, bool base = false);
    bool separate_base(EntityId e) const;
    abi_mangle::AbiTerminalKind operator_terminal(EntityId id) const;
    SymbolId fresh_symbol(const std::string& preferred);
    SignatureId signature(TypeId t, FunctionId owner = FunctionId());
    void function_body(EntityId e, bool base = false);
    void reset_lifetime(EntityId e);
    void destroy(EntityId destructor, TypeId t, Value object);
    void destroy_object(EntityId object, EntityId destructor);
    void clean_inline(std::uint32_t state, std::uint32_t stop);
    BlockId cleanup_suffix(std::uint32_t state, BlockId terminal);
    void emit_cleanups();
    void flush_cleanups();
    SlotId source_slot(EntityId e);
    Value guarded_call(Instruction i, const Operand* args, std::size_t count);
    void return_statement(NodeId n);
    void destructor_prologue(EntityId e);
    void destructor_finish(EntityId e);
    void destroy_subobjects(EntityId e);
    void finish_constructor_handlers();
    void constructor_cleanup(semantic::SubobjectAction action);
    semantic::Index initialized_units;
    unsigned initialization_expansion = 1;
    struct InitProjection { std::uint64_t offset; bool field; EntityId entity; TypeId element = 0;
        InitProjection(std::uint64_t o, bool f, EntityId e = 0) : offset(o), field(f), entity(e) {} };
    Value array_element(Value root, bool indirect, const std::vector<InitProjection>& path, Operand index, std::uint64_t stride);
    void array_construct(EntityId ctor, TypeId t, Value root, bool indirect, const std::vector<InitProjection>& path);
    void array_destroy(EntityId dtor, TypeId t, Value root, bool indirect, const std::vector<InitProjection>& path, bool subobject = false);
    Value initialization_address(Value root, bool indirect, const std::vector<InitProjection>& path);
    struct AggregateHelper { TypeId type; FunctionId function; std::uint32_t actions, count; };
    semantic::Index aggregate_helpers;
    std::vector<AggregateHelper> aggregate_definitions;
    std::vector<std::uint32_t> aggregate_actions;
    SymbolId aggregate_helper(std::uint32_t plan);
    bool call_aggregate_helper(std::uint32_t plan, Value location);
    void emit_aggregate_helpers();
    void initialize_plan(std::uint32_t plan, Value location);
    void repeat_initializer(std::uint32_t plan, Value base, std::uint64_t count = 0, TypeId type = 0);
    void aggregate_plan(std::uint32_t plan, Value root, bool indirect, std::vector<InitProjection>& path);
    void global_plan(std::uint32_t plan);
    void global_bit_field(std::uint32_t plan, std::uint64_t& bytes);
    void global_construction(NodeId n, TypeId t);
    bool constant_plan(std::uint32_t plan);
    Value string_element(NodeId source, TypeId element, std::uint64_t index);
    void aggregate_initialize(NodeId n, TypeId t, Value root, bool indirect, std::vector<InitProjection>& path);
    void constructor_body(EntityId e);
    void construct(EntityId ctor, NodeId init, Value object, bool base = false);
    bool constant_initializer(NodeId n, TypeId t);
    void global_initialization();
    void global_finalization();
    void global(EntityId e);
    void string_literal(NodeId n);
    void global_data(NodeId n, TypeId t);
    lowir_model::DataItem constant_data(NodeId n, TypeId t);
    IRType type(TypeId t);
    bool reference(TypeId t) const;
    Value emit(Instruction i, const Operand* args, std::size_t count);
    Value emit(Instruction i, const std::vector<Operand>& args);
    Value emit(Instruction i, std::initializer_list<Operand> args);
    Value emit(Opcode op, IRType t, std::initializer_list<Operand> args, Operation action = Operation::None);
    Value load(Value v);
    Value load_bit_field(Value v);
    Value store_bit_field(Value v, Value location);
    Value initialization_value(NodeId n, TypeId t);
    Value address(Value v);
    Value convert(Value v, TypeId target, bool fold_widen = false);
    Value coerce(Value v, IRType target, bool unsign = false, bool to_unsigned = false, bool fold_widen = false);
    Value converted(NodeId n, const semantic::Conversion& c);
    Value converted_value(Value value, const semantic::Conversion& conversion);
    Value user_conversion(NodeId n, const semantic::Conversion& conversion, Value destination = Value());
    Value incoming(NodeId n);
    Value expression(NodeId n, bool location = false);
    bool discarded_access(NodeId n);
    void discard(NodeId n, bool access = true);
    Value unary(NodeId n);
    Value binary(NodeId n, bool location);
    Value conditional(NodeId n, bool location, Value destination = Value(), std::uint32_t branches = 0);
    Value logical(NodeId n);
    Value call(NodeId n, Value destination = Value());
    Value floating_builtin(NodeId n);
    Value placement_new(NodeId n);
    Value operation(ETokenType op, Value a, Value b, TypeId result);
    Value binding(EntityId e);
    Value field(Value base, EntityId e, unsigned steps = 0);
    Value base_projection(Value base, unsigned steps);
    Value store(Value v, Value location);
    void initialize(NodeId n, TypeId t, Value location);
    void object(EntityId e);
    void statement(NodeId n);
    bool mark_control_entries(NodeId n);
    void condition(NodeId n, BlockId yes, BlockId no);
    void switch_statement(NodeId n);
    void collect_cases(NodeId n, std::vector<NodeId>& cases, NodeId& fallback);
    BlockId block();
    void start(BlockId b);
    void jump(BlockId b);
public:
    std::size_t control_work = 0, discard_work = 0;
    Procedural(syntax::Ast& a, semantic::Analyzer& s, IdentifierTable& ids, lowir_model::Program& out, Linkage& links);
    void run();
};
int emit_lowir(const std::string& output, const std::vector<std::string>& inputs, bool stats, bool audit = false);
} }
