#!/usr/bin/env python3
"""Make the dormant raw landing pad observable, preserving its instructions."""
from pathlib import Path
import hashlib,json,re,subprocess,sys
from reference112 import ROOT,HANDLER,ARRAY,reconstruct
WORK=Path(sys.argv[1]).resolve();WORK.mkdir(parents=True,exist_ok=True)
def run(cmd):
 p=subprocess.run(list(map(str,cmd)),capture_output=True,text=True,timeout=30)
 return dict(argv=list(map(str,cmd)),exit=p.returncode,stdout=p.stdout,stderr=p.stderr)
# Only the call sites/entry are controlled. Both complete landing-pad bodies
# are the reconstructed reference bytes, not generated by a student compiler.
host='''void throw_long() { throw 7; }
extern "C" void injected() { throw 9L; }
extern "C" int fixture_main();
int main() { return fixture_main(); }
'''
driver=WORK/'driver.cpp';driver.write_text(host);rows=[]
for name,text in zip(('original','revised'),reconstruct(HANDLER)):
 match=re.search(r'function @throw_long\([^\n]*\n.*?\n}',text,re.S);assert match
 text=text[:match.start()]+'declare '+match[0].splitlines()[0][:-2]+text[match.end():]
 text=text.replace('function @main() -> i32 [role=entry, binding=strong, keep_alias=yes]',
                   'function @fixture_main() -> i32 [binding=strong, object=fixture_main]')
 old='''    eh_cleanup ^catch_cleanup_15
    eh_end'''
 assert text.count(old)==1
 text='declare function @injected() -> void [linkage=c, binding=strong, object=injected]\n'+text.replace(old,'''    eh_cleanup ^catch_cleanup_15
    call void @injected()
    eh_end''')
 ir=WORK/(name+'.lowir');ir.write_text(text);obj=ir.with_suffix('.o');exe=WORK/name
 commands=[]
 for cmd in ([ROOT/'dev/cppgm++-ref','-c','-O0','-o',obj,ir],['g++','-no-pie',driver,obj,'-o',exe],[exe]):
  commands.append(run(cmd))
  if commands[-1]['exit']:break
 rows.append(dict(name=name,lowir_sha256=hashlib.sha256(text.encode()).hexdigest(),commands=commands))
 print(name,commands[-1]['exit'],commands[-1]['stderr'],flush=True)
 assert len(commands)==3 and commands[-1]['exit']==0,rows[-1]
# The supplied backend reconciles stacks at a shared catch-entry join. It
# therefore accepts both full versions above. Isolate the same three-region
# cleanup path with separate return continuations to expose the missing exit.
for ends in (2,3):
 text="""declare function @may_throw() -> void
function @reduced() -> void {
 block ^entry:
  eh_try ^outer
  eh_cleanup ^active_outer
  eh_cleanup ^active_inner
  call void @may_throw()
  eh_end
  eh_end
  eh_end
  return void
 block ^active_inner:
  eh_catch_all, 1
  ENDS
  return void
 block ^active_outer:
  eh_catch_all, 1
  eh_end
  eh_end
  return void
 block ^outer:
  eh_catch_all, 1
  return void
}
""".replace('ENDS','\n  '.join(['eh_end']*ends))
 ir=WORK/('region-count-%d.lowir'%ends);ir.write_text(text)
 command=run([ROOT/'dev/cppgm++-ref','-c','-O0','-o',ir.with_suffix('.o'),ir])
 assert (command['exit']==0 if ends==3 else command['exit']!=0 and 'protected region remains active' in command['stderr']),command
 rows.append(dict(name='region-count-'+str(ends),source=text,commands=[command]))
 print('region-count',ends,command['exit'],command['stderr'].strip(),flush=True)
# Both array forms must execute equivalently; PA16's explicit output contract,
# not an assertion of a C++ runtime difference, proves the required form.
for name,text in zip(('array-original','array-revised'),reconstruct(ARRAY)):
 ir=WORK/(name+'.lowir');ir.write_text(text);obj=ir.with_suffix('.o');exe=WORK/name
 commands=[run([ROOT/'dev/cppgm++-ref','-c','-O0','-o',obj,ir])]
 assert commands[-1]['exit']==0,commands
 commands.append(run(['g++','-no-pie',obj,'-o',exe]));assert commands[-1]['exit']==0,commands
 commands.append(run([exe]));assert commands[-1]['exit']==0,commands
 rows.append(dict(name=name,lowir_sha256=hashlib.sha256(text.encode()).hexdigest(),commands=commands))
 print(name,'PASS',flush=True)
(WORK/'results.json').write_text(json.dumps(dict(host=host,rows=rows),indent=2)+'\n')
