#define TRIVIAL(T,D,C,A) static_assert(__has_trivial_constructor(T)==D, "default"); static_assert(__has_trivial_copy(T)==C,"copy"); static_assert(__has_trivial_assign(T)==A,"assign")
#define NOTHROW(T,D,C,A) static_assert(__has_nothrow_constructor(T)==D,"default throws"); static_assert(__has_nothrow_copy(T)==C,"copy throws"); static_assert(__has_nothrow_assign(T)==A,"assign throws")
TRIVIAL(int,true,true,true);
TRIVIAL(const int,true,true,false);
TRIVIAL(volatile int,true,true,true);
TRIVIAL(int&,false,true,false);
TRIVIAL(int&&,false,true,false);
TRIVIAL(void,false,false,false);
TRIVIAL(int[3],true,true,true);
TRIVIAL(const int[],true,true,false);
using Function = int();
TRIVIAL(Function,false,false,false);
NOTHROW(int,true,true,true);
NOTHROW(int&,false,true,false);
NOTHROW(const int,true,true,false);
NOTHROW(void,false,false,false);
struct Plain { int value; };
TRIVIAL(Plain,true,true,true);
NOTHROW(Plain,true,true,true);
struct UserCopy { UserCopy(const UserCopy&) {} UserCopy(UserCopy&&) noexcept {} };
TRIVIAL(UserCopy,false,false,true);
NOTHROW(UserCopy,false,false,true);
struct DefaultThrow { DefaultThrow() noexcept(false) {} };
NOTHROW(DefaultThrow,false,true,true);
struct CopyThrow { CopyThrow() {} CopyThrow(const CopyThrow&) noexcept(false) {} };
NOTHROW(CopyThrow,false,false,true);
struct NoThrow { NoThrow() noexcept {} NoThrow(const NoThrow&) noexcept {} NoThrow& operator=(const NoThrow&) noexcept {return *this;} };
TRIVIAL(NoThrow,false,false,false);
NOTHROW(NoThrow,true,true,true);
struct BothCopies { BothCopies(BothCopies&) {} BothCopies(const BothCopies&) noexcept {} };
NOTHROW(BothCopies,false,false,true);
struct BothAssignments { BothAssignments& operator=(BothAssignments&) {return *this;} BothAssignments& operator=(const BothAssignments&) noexcept {return *this;} };
NOTHROW(BothAssignments,true,true,false);
struct Base { NoThrow data; };
TRIVIAL(Base,false,false,false);
NOTHROW(Base,true,true,true);
struct Derived : Base { CopyThrow data; };
NOTHROW(Derived,false,false,true);
struct Virtual { virtual void f(); };
TRIVIAL(Virtual,false,false,false);
struct Initializer { int data=1; };
TRIVIAL(Initializer,false,true,true);
struct Private { private: Private() noexcept; Private(const Private&) noexcept; Private& operator=(const Private&) noexcept; };
NOTHROW(Private,true,true,true);
static_assert(!__is_constructible(Private),"legacy trait must not erase access");
struct Deleted { Deleted()=delete; Deleted(const Deleted&)=delete; Deleted& operator=(const Deleted&)=delete; };
TRIVIAL(Deleted,true,true,true);
NOTHROW(Deleted,true,true,true);
static_assert(!__is_constructible(Deleted),"legacy trait must not erase deletion");
struct Ref { int& member; };
struct Const { const int member; };
TRIVIAL(Ref,true,true,true);
TRIVIAL(Const,true,true,true);
struct ThrowingDestructor { ~ThrowingDestructor() noexcept(false) {} };
TRIVIAL(ThrowingDestructor,true,true,true);
NOTHROW(ThrowingDestructor,true,true,true);
int called();
struct DefaultArgument { DefaultArgument(int=called()) noexcept {} };
NOTHROW(DefaultArgument,true,true,true);
struct Late { Late(); Late(const Late&); Late& operator=(const Late&); };
Late::Late()=default;
Late::Late(const Late&)=default;
Late& Late::operator=(const Late&)=default;
TRIVIAL(Late,false,false,false);
int main(){return 0;}
