#define REF(T,U,B,D,C) static_assert(__reference_binds_to_temporary(T,U)==B,"binds"); static_assert(__reference_constructs_from_temporary(T,U)==D,"direct"); static_assert(__reference_converts_from_temporary(T,U)==C,"copy")
REF(int,int,false,false,false);
REF(int&,int,false,false,false);
REF(const int&,int,true,true,true);
REF(int&&,int,true,true,true);
REF(const int&,int&&,false,false,false);
REF(const int&,int&,false,false,false);
REF(const int&,long&,true,true,true);
REF(int&&,long&,true,true,true);
REF(volatile int&,int,false,false,false);
REF(const volatile int&,int,false,false,false);
REF(const int&,volatile int&,false,false,false);
REF(const int&,void,false,false,false);
using Function = int();
REF(Function&,Function,false,false,false);
REF(Function&&,Function,false,false,false);
struct S {};
struct Derived : S {};
struct Hidden : private S {};
REF(const S&,S,true,true,true);
REF(S&&,S,true,true,true);
REF(S&&,S&&,false,false,false);
REF(const S&,Derived,true,true,true);
REF(const S&,Derived&,false,false,false);
REF(const S&,Hidden,false,false,false);
struct Value { operator int() const; };
struct Lvalue { operator int&() const; };
struct Rvalue { operator int&&() const; };
struct ExplicitValue { explicit operator int() const; };
struct ExplicitRef { explicit operator int&() const; };
struct ExplicitRRef { explicit operator int&&() const; };
REF(const int&,Value,true,true,true);
REF(const int&,Lvalue,false,false,false);
REF(const long&,Lvalue,true,true,true);
REF(const int&,Rvalue,false,false,false);
REF(const int&,ExplicitValue,true,true,false);
REF(const int&,ExplicitRef,false,false,false);
REF(const int&,ExplicitRRef,false,false,false);
REF(const long&,ExplicitRef,false,false,false);
struct ClassValue { operator S() const; };
REF(const S&,ClassValue,true,true,true);
struct CopyOnly { CopyOnly(int); };
REF(const CopyOnly&,int,true,true,true);
struct DirectOnly { explicit DirectOnly(int); };
REF(const DirectOnly&,int,false,false,false);
struct DeletedConversion { operator int() const=delete; };
REF(const int&,DeletedConversion,false,false,false);
struct PrivateConversion { private: operator int() const; };
REF(const int&,PrivateConversion,false,false,false);
struct Promotion { operator short() const; operator long() const; };
REF(const int&,Promotion,true,true,true);
struct Ambiguous { operator unsigned int() const; operator long() const; };
REF(const int&,Ambiguous,false,false,false);
struct DeletedDestructor { ~DeletedDestructor()=delete; };
REF(const DeletedDestructor&,DeletedDestructor,false,false,false);
REF(const DeletedDestructor&,DeletedDestructor&,false,false,false);
using Array=int[2];
REF(const Array&,Array&,false,false,false);
int main(){return 0;}
