#!/usr/bin/env python3
"""Captureless closure identity, body, specialization and value consumers."""
from pathlib import Path
import sys
import entity_controls as runner

runner.GOOD = {
 'void_body': 'int n;int main(){auto f=[] {n=7;};f();return n!=7;}',
 'const_call': 'int main(){const auto f=[] {return 7;};return f()!=7;}',
 'parameters': 'int main(){auto f=[](int x,char y){return x+y;};return f(3,4)!=7;}',
 'ellipsis_signature': 'int main(){auto f=[](int n,...){return n;};return f(7,3)!=7;}',
 'mutable_call': 'int main(){auto f=[]()mutable{return 7;};return f()!=7;}',
 'mutable_const_surrogate': 'int main(){const auto f=[]()mutable{return 7;};return f()!=7;}',
 'trailing_reference': 'int n=7;int main(){auto f=[]()->int&{return n;};f()=9;return n!=9;}',
 'trailing_control': 'int main(){auto f=[](int n)->int{if(n)return 7;return 3;};return f(1)!=7||f(0)!=3;}',
 'noexcept_call': 'int main(){auto f=[]()noexcept{return 7;};static_assert(noexcept(f()),"call");return f()!=7;}',
 'noexcept_expression': 'int main(){auto f=[]()noexcept(sizeof(int)==4){return 7;};static_assert(noexcept(f()),"call");return f()!=7;}',
 'throwing_call': 'int main(){auto f=[]{return 7;};static_assert(!noexcept(f()),"call");return f()!=7;}',
 'local_constant': 'int main(){const int n=7;auto f=[]{return n;};return f()!=7;}',
 'nested_body': 'int n;int main(){auto f=[] {auto g=[] {n=7;};g();};f();return n!=7;}',
 'copy_value': 'int main(){auto f=[]{return 7;};auto g=f;return g()!=7;}',
 'value_argument': 'template<class F>int run(F f){return f();}int main(){return run([]{return 7;})!=7;}',
 'ref_argument': 'template<class F>int run(F const&f){return f();}int main(){return run([]{return 7;})!=7;}',
 'distinct_identities': 'template<class,class>struct Same{static const bool value=false;};template<class T>struct Same<T,T>{static const bool value=true;};int main(){auto f=[]{return 3;};auto g=[]{return 7;};static_assert(!Same<decltype(f),decltype(g)>::value,"identity");return f()+g()!=10;}',
 'specialization_body': 'template<int N>int run(){auto f=[]{return N;};return f();}int main(){return run<3>()!=3||run<7>()!=7;}',
 'specialization_parameter': 'template<class T>int run(){auto f=[](T n){return n;};return f(7);}int main(){return run<int>()!=7||run<long>()!=7;}',
 'specialization_local': 'template<class T>int run(){auto f=[](T n)->int{T x=n;return x;};return f(7);}int main(){return run<int>()!=7||run<long>()!=7;}',
 'declaration_lookup': 'int f(int){return 7;}template<class T>int run(){auto g=[]{return f(1);};return g();}int f(long){return 3;}int main(){return run<int>()!=7;}',
 'class_return': 'struct S{int n;S(int n):n(n){}};int main(){auto f=[]{return S(7);};return f().n!=7;}',
 'unused_body_demand': 'int n;int step(){n=7;return 0;}int main(){auto f=[]{return step();};return n;}',
 'body_lifetime': 'int n;struct S{~S(){++n;}};int main(){auto f=[]{S x;};f();return n!=1;}',
 'function_pointer': 'int main(){int(*f)(int)=[](int n){return n+2;};return f(5)!=7;}',
 'pointer_reference_return': 'int n=7;int main(){int&(*f)()=[]()->int&{return n;};f()=9;return n!=9;}',
 'pointer_class_result': 'int n;struct S{int value;S(int x):value(x){}~S(){++n;}};int main(){S(*f)(int)=[](int x){return S(x);};int r=f(7).value;return r!=7||n!=1;}',
 'pointer_class_parameter': 'int n;struct S{int value;S(int x):value(x){}~S(){++n;}};int main(){int(*f)(S)=[](S x){return x.value;};int r=f(S(7));return r!=7||n!=1;}',
 'pointer_mutable': 'int main(){int(*f)()=[]()mutable{return 7;};return f()!=7;}',
 'namespace_closure': 'int n;int run(){return 7;}int value=[]{return run();}();int main(){return value!=7;}',
 'local_static': 'int run(){static auto f=[]{return 7;};return f();}int main(){return run()!=7||run()!=7;}',
 'private_context': 'class S{static int f(){return 7;}public:int run(){auto g=[]{return f();};return g();}};int main(){S x;return x.run()!=7;}',
 'unevaluated_local': 'int run(int n){auto f=[]{return sizeof(n);};return f();}int main(){return run(7)!=4;}',
 'unevaluated_this': 'struct S{int n;int run(){auto f=[]{return sizeof(*this);};return f();}};int main(){S s;return s.run()!=4;}',
 'unevaluated_member': 'struct S{int n;int run()const{auto f=[]{return sizeof(n);};return f();}};int main(){S s;return s.run()!=4;}',
 'template_unevaluated_this': 'template<class T>struct S{T n;int run(){auto f=[]{return sizeof(*this);};return f();}};int main(){S<long>s;return s.run()!=8;}',
 'nested_unevaluated_this': 'struct S{int n;int run(){auto f=[]()->int{auto g=[]{return sizeof(*this);};return g();};return f();}};int main(){S s;return s.run()!=4;}',
 'auto_reference': 'int main(){auto f=[]{return 7;};auto&g=f;const auto&h=f;return g()!=7||h()!=7;}',
 'auto_forward_reference': 'int main(){auto f=[]{return 7;};auto&&g=f;return g()!=7;}',
 'auto_pointer': 'int main(){auto f=[]{return 7;};auto*p=&f;return (*p)()!=7;}',
 'template_nested_lambda': 'template<int N>int run(){auto f=[]()->int{auto g=[]{return N;};return g();};return f();}int main(){return run<3>()!=3||run<7>()!=7;}',
 'lambda_to_class_conversion': 'int n;struct W{template<class F>W(F f){n=f();}~W(){++n;}};void take(W const&){}int main(){take([]{return 7;});return n!=8;}',
 'template_distinct_static': 'template<int N>int run(){auto f=[]()->int{static int n=N;return n++;};return f();}int main(){return run<3>()!=3||run<7>()!=7||run<3>()!=4;}',
 'parameter_decltype_return': 'int main(){auto f=[](int n)->decltype(n){return n;};return f(7)!=7;}',
 'template_parameter_decltype_return': 'template<class T>int run(){auto f=[](T n)->decltype(n){return n;};return f(7);}int main(){return run<int>()!=7||run<long>()!=7;}',
 'lambda_parameter_pack': 'template<class...T>int run(T...n){auto f=[](T...x){return sizeof...(x);};return f(n...);}int main(){return run()!=0||run(1,2L)!=2;}',
 'auto_scalar_shapes': 'int f(){return 7;}int main(){const int n=7;auto x=n;auto&y=n;auto*p=&n;auto fn=f;return x!=7||y!=7||*p!=7||fn()!=7;}',
 'auto_shared_deduction': 'int main(){int n=7;auto*p=&n,q=n;return *p!=7||q!=7;}',
}
runner.BAD = {
 'uncaptured_local': 'int main(){int n=7;auto f=[]{return n;};return f();}',
 'uncaptured_parameter': 'int run(int n){auto f=[]{return n;};return f();}',
 'uncaptured_this': 'struct S{int n;int f(){auto g=[]{return this->n;};return g();}};int main(){S s;return s.f();}',
 'default_construction': 'int main(){auto f=[]{return 7;};decltype(f) g;return g();}',
 'copy_assignment': 'int main(){auto f=[]{return 7;};auto g=f;g=f;return g();}',
 'bad_body': 'int main(){auto f=[]{return missing;};}',
 'default_parameter': 'int main(){auto f=[](int n=7){return n;};return f();}',
 'unused_default_parameter': 'int main(){auto f=[](int n=7){return n;};}',
 'uncaptured_constant_address': 'int main(){const int n=7;auto f=[]{return &n;};return *f();}',
 'unevaluated_lambda': 'int main(){return sizeof([]{});}',
 'outer_loop_break': 'int main(){for(;;){auto f=[]{break;};break;}}',
 'inferred_multiple_returns': 'int main(){auto f=[](int n){if(n)return 7;return 3;};return f(1);}',
 'unused_template_bad_body': 'template<class T>int run(){auto f=[]{return unknown;};return 0;}int main(){}',
 'unused_template_default_parameter': 'template<class T>int run(){auto f=[](int n=7){return n;};return 0;}int main(){}',
 'lambda_const_suffix': 'int main(){auto f=[]()const{return 7;};return f();}',
 'lambda_auto_parameter': 'int main(){auto f=[](auto n){return n;};return f(7);}',
 'auto_self_reference': 'int main(){auto n=n;return n;}',
 'auto_shadowed_self': 'int n=7;int main(){auto n=n;return n;}',
 'auto_inconsistent_deduction': 'int main(){auto n=7,m=7L;return n+m;}',
 'auto_missing_initializer': 'int main(){auto n;return n;}',
 'auto_deleted_function_address': 'int f()=delete;auto p=&f;int main(){}',
 'auto_deleted_function_decay': 'int f()=delete;auto p=f;int main(){}',
 'auto_deleted_member_address': 'struct S{int f()=delete;};auto p=&S::f;int main(){}',
}
if __name__ == '__main__':
 sys.exit(0 if runner.run(Path(sys.argv[1]).resolve(),Path(sys.argv[2])) else 1)
