#!/usr/bin/env python3
"""Exact partial selection and typed argument substitution controls."""
from pathlib import Path
import sys
import entity_controls as runner
runner.GOOD={
'variable_cv_exact': '''template<class T>const int v=0;template<class T>const int v<T const> =1;template<class T>const int v<T volatile> =2;template<class T>const int v<T const volatile> =3;static_assert(v<int> ==0 && v<const int> ==1 && v<volatile int> ==2 && v<const volatile int> ==3,"cv");int main(){return 0;}''',
'variable_fixed_cv': '''template<class A,class B>const int v=0;template<class T>const int v<int const,T> =1;static_assert(v<int,char> ==0 && v<int const,char> ==1 && v<int const volatile,char> ==0,"fixed cv");int main(){return 0;}''',
'variable_pack_forward': '''template<class T,class...U>const int v=sizeof...(U);template<class T,class...U>const int v<T const,U...> =v<T,U...>+10;static_assert(v<int const> ==10 && v<char const,int,double> ==12,"pack");int main(){return v<char const,int>-11;}''',
'variable_value_pack': '''template<int...N>const int v=sizeof...(N);template<int...N>const int v<1,N...> =v<N...>+10;static_assert(v<> ==0 && v<1> ==10 && v<1,2,3> ==12 && v<2,3> ==2,"value pack");int main(){return 0;}''',
'variable_order': '''template<class...>struct L{};template<class T>const int v=0;template<class...T>const int v<L<T...>> =1;template<class T,class...U>const int v<L<T,U...>> =2;static_assert(v<L<>> ==1 && v<L<int>> ==2 && v<L<int,char>> ==2,"order");int main(){return 0;}''',
'variable_repeated_pack': '''template<class...>struct L{};template<class A,class B>const bool v=false;template<class...T>const bool v<L<T...>,L<T...>> =true;static_assert(v<L<>,L<>> && v<L<int,char>,L<int,char>> && !v<L<int>,L<char>>,"repeat");int main(){return 0;}''',
'value_argument_chain': '''template<class...T>const bool a=sizeof...(T)==2;template<bool B>const int b=B?7:3;template<class...T>const int c=b<a<T...>>;static_assert(c<> ==3 && c<int,char> ==7,"value args");int main(){return c<int,char>-7;}''',
'member_alias_template_identity': '''template<class...>struct L{};template<class...T>struct Owner{template<class...U>using F=L<T...,U...>;};template<template<class...>class F>struct Apply{using type=F<int>;};template<class T>using A=typename Apply<T::template F>::type;template<class,class>struct Same{static const bool v=false;};template<class T>struct Same<T,T>{static const bool v=true;};static_assert(Same<A<Owner<>>,L<int>>::v && Same<A<Owner<char>>,L<char,int>>::v,"member identity");int main(){return 0;}''',
'member_partial_owner': '''template<class T>struct A{template<class U,class...V>struct B;};template<class X>template<class Y,class R>struct A<X>::B<Y,R()>{static const int n=sizeof(X)+sizeof(Y);};static_assert(A<char>::B<int,void()>::n==5 && A<int>::B<char,int()>::n==5,"owner");int main(){return 0;}''',
'variable_cv_array': '''template<class>const int v=0;template<class T>const int v<T const> =1;static_assert(v<int[2]> ==0 && v<const int[2]> ==1 && v<int()> ==0 && v<int() const> ==0,"cv array");int main(){return 0;}''',
}
runner.GOOD.update({
'pack_query_partial': "template<bool B,class T=void>struct Enable{};template<class T>struct Enable<true,T>{using type=T;};template<bool B>using E=typename Enable<B>::type;template<class...>struct L{};template<class...T>struct O{template<class U,class=void>struct I{static const bool v=false;};template<class...U>struct I<L<U...>,E<sizeof...(U)==sizeof...(T)>>{static const bool v=true;};};static_assert(O<>::I<L<>>::v && !O<>::I<L<int>>::v && O<int,char>::I<L<long,short>>::v && !O<int>::I<L<>>::v, \"sizes\");int main(){return O<int>::I<L<char>>::v?0:1;}",
'qualified_alias_completion': "template<class T,T V>struct C{static const T value=V;};template<bool B>using Bool=C<bool,B>;struct Base{template<class U>static char(&f(U*))[3];};template<class T>struct A{using B=Bool<sizeof(T::f((int*)0))==3>;static_assert(B::value,\"alias completion\");};A<Base>a;int main(){return 0;}",
'member_partial_body': "template<class T>struct A{template<class U,class...V>struct B;};template<class X>template<class Y,class R>struct A<X>::B<Y,R()>{int f(){return sizeof(X)+sizeof(Y);}};int main(){A<char>::B<int,void()>b;return b.f()-5;}",
})
runner.BAD={
'variable_ambiguity': 'template<class A,class B>const int v=0;template<class T>const int v<int,T> =1;template<class T>const int v<T,int> =2;static_assert(v<int,int> ==1,"ambiguous");',
'variable_unrelated_template': 'template<class>struct A{};template<class>struct B{};template<class>const int v=0;template<class T>const int v<A<T>> =1;static_assert(v<B<int>> ==1,"distinct templates");',
'variable_repeated_mismatch': 'template<class A,class B>const int v=0;template<class T>const int v<T,T> =1;static_assert(v<int,const int> ==1,"exact repetition");',
}
runner.GOOD.update({'pack_size_alias_head': 'template<bool B,class=void>struct E{};template<class T>struct E<true,T>{using type=T;};template<bool B>using En=typename E<B>::type;template<class...>struct L{};template<class T,class=void>struct A{static const int v=0;};template<class...T>struct A<L<T...>,En<(sizeof...(T)>1)>>{static const int v=1;};static_assert(A<L<>>::v==0 && A<L<int>>::v==0 && A<L<int,char>>::v==1,"pack shape");int main(){return 0;}', 'variable_nondeduced_size': 'template<class T,unsigned long N>const int v=0;template<class T>const int v<T,sizeof(T)> =1;static_assert(v<char,1> ==1 && v<int,4> ==1 && v<int,1> ==0,"nondeduced query");int main(){return 0;}', 'variable_source_order': 'template<class T>const int v=0;template<class T>const int v<T const volatile> =3;template<class T>const int v<T const> =1;template<class T>const int v<T volatile> =2;static_assert(v<int const volatile> ==3,"order independent");int main(){return 0;}', 'member_partial_renamed_alias': 'template<class T>struct A{template<class U>struct B;};template<class X>template<class Y>struct A<X>::B<Y*>{using type=X;};template<class,class>struct S{static const bool v=false;};template<class T>struct S<T,T>{static const bool v=true;};static_assert(S<A<char>::B<int*>::type,char>::v,"outer alias");int main(){return 0;}'})
runner.BAD.update({'variable_partial_duplicate_unused': 'template<class T>const int v=0;template<class T>const int v<T*> =1;template<class U>const int v<U*> =2;', 'variable_partial_equivalent_primary': 'template<class T>const int v=0;template<class U>const int v<U> =1;', 'variable_partial_nondeducible': 'template<class T>const int v=0;template<class U>const int v<int> =1;', 'variable_partial_default': 'template<class T>const int v=0;template<class U=int>const int v<U*> =1;', 'member_partial_duplicate_unused': 'template<class T>struct A{template<class U>struct B;};template<class X>template<class Y>struct A<X>::B<Y*>{};template<class X>template<class Y>struct A<X>::B<Y*>{};', 'partial_pack_size_duplicate': 'template<bool B,class=void>struct E{};template<class T>struct E<true,T>{using type=T;};template<bool B>using En=typename E<B>::type;template<class...>struct L{};template<class T,class=void>struct A{};template<class...T>struct A<L<T...>,En<(sizeof...(T)>1)>>{};template<class...U>struct A<L<U...>,En<(sizeof...(U)>1)>>{};'})
runner.GOOD.update({'qualified_explicit_value_query': 'struct A{template<int N>static char(&f())[N];};template<class T>struct Q{static const int v=sizeof(T::template f<3>());};static_assert(Q<A>::v==3,"explicit query args");int main(){return 0;}', 'qualified_explicit_type_query': 'struct A{template<class U>static U f();};template<class T>struct Q{static const int v=sizeof(T::template f<long>());};static_assert(Q<A>::v==8,"explicit type query args");int main(){return 0;}', 'member_explicit_query': 'struct A{template<int N>char(&f())[N];};template<class T>struct Q{static const int v=sizeof(((T*)0)->template f<4>());};static_assert(Q<A>::v==4,"member query args");int main(){return 0;}', 'qualified_non_template_decltype': 'struct A{static int f(char);};template<class T>struct Q{using type=decltype(T::f);};template<class,class>struct S{static const bool v=false;};template<class T>struct S<T,T>{static const bool v=true;};static_assert(S<Q<A>::type,int(char)>::v,"function type");int main(){return 0;}', 'volatile_boolean_condition': 'struct A{static const volatile bool v;};const volatile bool A::v=true;int main(){return A::v?0:1;}'})
if __name__=='__main__':
 sys.exit(0 if runner.run(Path(sys.argv[1]).resolve() if len(sys.argv)>1 else runner.ROOT/'dev/cppgm++',Path(sys.argv[2]) if len(sys.argv)>2 else Path('/tmp/pa17-selection-controls')) else 1)
