struct E{}; template<int N> struct Tag{};
struct Many { char c;
[[no_unique_address]] Tag<0> t0;
[[no_unique_address]] Tag<1> t1;
[[no_unique_address]] Tag<2> t2;
[[no_unique_address]] Tag<3> t3;
[[no_unique_address]] Tag<4> t4;
[[no_unique_address]] Tag<5> t5;
[[no_unique_address]] Tag<6> t6;
[[no_unique_address]] Tag<7> t7;
[[no_unique_address]] Tag<8> t8;
[[no_unique_address]] Tag<9> t9;
[[no_unique_address]] Tag<10> t10;
[[no_unique_address]] Tag<11> t11;
[[no_unique_address]] Tag<12> t12;
[[no_unique_address]] Tag<13> t13;
[[no_unique_address]] Tag<14> t14;
[[no_unique_address]] Tag<15> t15;
[[no_unique_address]] Tag<16> t16;
[[no_unique_address]] Tag<17> t17;
[[no_unique_address]] Tag<18> t18;
[[no_unique_address]] Tag<19> t19;
[[no_unique_address]] Tag<20> t20;
[[no_unique_address]] Tag<21> t21;
[[no_unique_address]] Tag<22> t22;
[[no_unique_address]] Tag<23> t23;
[[no_unique_address]] Tag<24> t24;
[[no_unique_address]] Tag<25> t25;
[[no_unique_address]] Tag<26> t26;
[[no_unique_address]] Tag<27> t27;
[[no_unique_address]] Tag<28> t28;
[[no_unique_address]] Tag<29> t29;
[[no_unique_address]] Tag<30> t30;
[[no_unique_address]] Tag<31> t31;
[[no_unique_address]] Tag<32> t32;
[[no_unique_address]] Tag<33> t33;
[[no_unique_address]] Tag<34> t34;
[[no_unique_address]] Tag<35> t35;
[[no_unique_address]] Tag<36> t36;
[[no_unique_address]] Tag<37> t37;
[[no_unique_address]] Tag<38> t38;
[[no_unique_address]] Tag<39> t39;
[[no_unique_address]] Tag<40> t40;
[[no_unique_address]] Tag<41> t41;
[[no_unique_address]] Tag<42> t42;
[[no_unique_address]] Tag<43> t43;
[[no_unique_address]] Tag<44> t44;
[[no_unique_address]] Tag<45> t45;
[[no_unique_address]] Tag<46> t46;
[[no_unique_address]] Tag<47> t47;
[[no_unique_address]] Tag<48> t48;
[[no_unique_address]] Tag<49> t49;
[[no_unique_address]] Tag<50> t50;
[[no_unique_address]] Tag<51> t51;
[[no_unique_address]] Tag<52> t52;
[[no_unique_address]] Tag<53> t53;
[[no_unique_address]] Tag<54> t54;
[[no_unique_address]] Tag<55> t55;
[[no_unique_address]] Tag<56> t56;
[[no_unique_address]] Tag<57> t57;
[[no_unique_address]] Tag<58> t58;
[[no_unique_address]] Tag<59> t59;
[[no_unique_address]] Tag<60> t60;
[[no_unique_address]] Tag<61> t61;
[[no_unique_address]] Tag<62> t62;
[[no_unique_address]] Tag<63> t63;
[[no_unique_address]] Tag<64> t64;
[[no_unique_address]] Tag<65> t65;
[[no_unique_address]] Tag<66> t66;
[[no_unique_address]] Tag<67> t67;
[[no_unique_address]] Tag<68> t68;
[[no_unique_address]] Tag<69> t69;
[[no_unique_address]] E e; };
struct H { [[no_unique_address]] E e; };
struct Wrapped {char c; Many m; [[no_unique_address]] E e;};
struct Arrays { char c; H a[1000000]; [[no_unique_address]] E e; };
struct Repeated { char c; [[no_unique_address]] E e0;[[no_unique_address]] E e1;[[no_unique_address]] E e2;[[no_unique_address]] E e3;[[no_unique_address]] E e4;[[no_unique_address]] E e5;[[no_unique_address]] E e6;[[no_unique_address]] E e7;[[no_unique_address]] E e8;[[no_unique_address]] E e9;[[no_unique_address]] E e10;[[no_unique_address]] E e11;[[no_unique_address]] E e12;[[no_unique_address]] E e13;[[no_unique_address]] E e14;[[no_unique_address]] E e15;[[no_unique_address]] E e16;[[no_unique_address]] E e17;[[no_unique_address]] E e18;[[no_unique_address]] E e19;[[no_unique_address]] E e20;[[no_unique_address]] E e21;[[no_unique_address]] E e22;[[no_unique_address]] E e23;[[no_unique_address]] E e24;[[no_unique_address]] E e25;[[no_unique_address]] E e26;[[no_unique_address]] E e27;[[no_unique_address]] E e28;[[no_unique_address]] E e29;[[no_unique_address]] E e30;[[no_unique_address]] E e31;[[no_unique_address]] E e32;[[no_unique_address]] E e33;[[no_unique_address]] E e34;[[no_unique_address]] E e35;[[no_unique_address]] E e36;[[no_unique_address]] E e37;[[no_unique_address]] E e38;[[no_unique_address]] E e39;[[no_unique_address]] E e40;[[no_unique_address]] E e41;[[no_unique_address]] E e42;[[no_unique_address]] E e43;[[no_unique_address]] E e44;[[no_unique_address]] E e45;[[no_unique_address]] E e46;[[no_unique_address]] E e47;[[no_unique_address]] E e48;[[no_unique_address]] E e49;[[no_unique_address]] E e50;[[no_unique_address]] E e51;[[no_unique_address]] E e52;[[no_unique_address]] E e53;[[no_unique_address]] E e54;[[no_unique_address]] E e55;[[no_unique_address]] E e56;[[no_unique_address]] E e57;[[no_unique_address]] E e58;[[no_unique_address]] E e59;[[no_unique_address]] E e60;[[no_unique_address]] E e61;[[no_unique_address]] E e62;[[no_unique_address]] E e63;[[no_unique_address]] E e64;[[no_unique_address]] E e65;[[no_unique_address]] E e66;[[no_unique_address]] E e67;[[no_unique_address]] E e68;[[no_unique_address]] E e69;[[no_unique_address]] E e70;[[no_unique_address]] E e71;[[no_unique_address]] E e72;[[no_unique_address]] E e73;[[no_unique_address]] E e74;[[no_unique_address]] E e75;[[no_unique_address]] E e76;[[no_unique_address]] E e77;[[no_unique_address]] E e78;[[no_unique_address]] E e79;[[no_unique_address]] E e80;[[no_unique_address]] E e81;[[no_unique_address]] E e82;[[no_unique_address]] E e83;[[no_unique_address]] E e84;[[no_unique_address]] E e85;[[no_unique_address]] E e86;[[no_unique_address]] E e87;[[no_unique_address]] E e88;[[no_unique_address]] E e89;[[no_unique_address]] E e90;[[no_unique_address]] E e91;[[no_unique_address]] E e92;[[no_unique_address]] E e93;[[no_unique_address]] E e94;[[no_unique_address]] E e95;[[no_unique_address]] E e96;[[no_unique_address]] E e97;[[no_unique_address]] E e98;[[no_unique_address]] E e99;[[no_unique_address]] E e100;[[no_unique_address]] E e101;[[no_unique_address]] E e102;[[no_unique_address]] E e103;[[no_unique_address]] E e104;[[no_unique_address]] E e105;[[no_unique_address]] E e106;[[no_unique_address]] E e107;[[no_unique_address]] E e108;[[no_unique_address]] E e109;[[no_unique_address]] E e110;[[no_unique_address]] E e111;[[no_unique_address]] E e112;[[no_unique_address]] E e113;[[no_unique_address]] E e114;[[no_unique_address]] E e115;[[no_unique_address]] E e116;[[no_unique_address]] E e117;[[no_unique_address]] E e118;[[no_unique_address]] E e119;[[no_unique_address]] E e120;[[no_unique_address]] E e121;[[no_unique_address]] E e122;[[no_unique_address]] E e123;[[no_unique_address]] E e124;[[no_unique_address]] E e125;[[no_unique_address]] E e126;[[no_unique_address]] E e127;[[no_unique_address]] E e128;[[no_unique_address]] E e129;[[no_unique_address]] E e130;[[no_unique_address]] E e131;[[no_unique_address]] E e132;[[no_unique_address]] E e133;[[no_unique_address]] E e134;[[no_unique_address]] E e135;[[no_unique_address]] E e136;[[no_unique_address]] E e137;[[no_unique_address]] E e138;[[no_unique_address]] E e139;[[no_unique_address]] E e140;[[no_unique_address]] E e141;[[no_unique_address]] E e142;[[no_unique_address]] E e143;[[no_unique_address]] E e144;[[no_unique_address]] E e145;[[no_unique_address]] E e146;[[no_unique_address]] E e147;[[no_unique_address]] E e148;[[no_unique_address]] E e149;[[no_unique_address]] E e150;[[no_unique_address]] E e151;[[no_unique_address]] E e152;[[no_unique_address]] E e153;[[no_unique_address]] E e154;[[no_unique_address]] E e155;[[no_unique_address]] E e156;[[no_unique_address]] E e157;[[no_unique_address]] E e158;[[no_unique_address]] E e159;[[no_unique_address]] E e160;[[no_unique_address]] E e161;[[no_unique_address]] E e162;[[no_unique_address]] E e163;[[no_unique_address]] E e164;[[no_unique_address]] E e165;[[no_unique_address]] E e166;[[no_unique_address]] E e167;[[no_unique_address]] E e168;[[no_unique_address]] E e169;[[no_unique_address]] E e170;[[no_unique_address]] E e171;[[no_unique_address]] E e172;[[no_unique_address]] E e173;[[no_unique_address]] E e174;[[no_unique_address]] E e175;[[no_unique_address]] E e176;[[no_unique_address]] E e177;[[no_unique_address]] E e178;[[no_unique_address]] E e179;[[no_unique_address]] E e180;[[no_unique_address]] E e181;[[no_unique_address]] E e182;[[no_unique_address]] E e183;[[no_unique_address]] E e184;[[no_unique_address]] E e185;[[no_unique_address]] E e186;[[no_unique_address]] E e187;[[no_unique_address]] E e188;[[no_unique_address]] E e189;[[no_unique_address]] E e190;[[no_unique_address]] E e191;[[no_unique_address]] E e192;[[no_unique_address]] E e193;[[no_unique_address]] E e194;[[no_unique_address]] E e195;[[no_unique_address]] E e196;[[no_unique_address]] E e197;[[no_unique_address]] E e198;[[no_unique_address]] E e199; };
static_assert(sizeof(Many)==1 && sizeof(Wrapped)==2 && sizeof(Arrays)==1000001,"exact fallback and compact array footprint");
static_assert(__builtin_offsetof(Wrapped,e)==0 && __builtin_offsetof(Arrays,e)==0,"address-directed fallback");
static_assert(sizeof(Repeated)==200 && __builtin_offsetof(Repeated,e199)==199,"monotonic repeated placements");
int main(){return 0;}
