#!/usr/bin/env python3
"""Render the preserved PA23/O0 lifecycle performance observations."""
from pathlib import Path
import json,statistics
ROOT=Path(__file__).resolve().parents[2]
d=json.loads((ROOT/'student.tests/pa23/performance122.json').read_text());repeat=json.loads((ROOT/'student.tests/pa23/performance122-repeat.json').read_text())
lines=['# PA23/O0 performance — handoff 122','',
'Implementation **a04a8cae**, compared with turn entry **26b96f27**. Both binaries, all source inputs, hashes, flags, CPU affinity, platform, observations and checked results are frozen in [initial observations](../student.tests/pa23/performance122.json) and [longer repeats](../student.tests/pa23/performance122-repeat.json). The binaries remain at `/tmp/pa23-122/{entry,sealed}`; their SHA-256 values are also in the committed data.','',
'## Protocol','',
'[`benchmark122.py`](../student.tests/pa23/benchmark122.py) uses one warmup per lane, four A/A samples and four wall-time ABBA blocks, with compilation and executable execution measured separately. The repeat uses eight ABBA blocks, the same binaries and template source, and 12 million deletion iterations instead of one million. The original short measurements are preserved. Runtime inputs are volatile and results are checked; no workload times a constant or dead loop. The compiler is built with the existing dev Makefile defaults (`g++ -std=gnu++11 -Wall -O3`); measured source compilation uses `--emit-lowir -O0`.','',
'All lanes execute correct equivalent programs. The supplied backend compiles our LowIR to native objects and the host linker links those objects. The source frontend never delegates implementation. Telemetry plus explicit validation preserves each LowIR hash. The [validation record](../student.tests/pa23/validation122.json) also hashes native `.text` sections. Small source TUs and execution-only smoke checks are startup-sensitive; no speed claim relies on them.','',
'## Initial observations','',
'Times are median milliseconds; compiler memory is peak KiB; native text is bytes. Pair ranges include every ABBA block.','',
'| Input | Compiler A → B ms | RSS A → B KiB | Compiler paired B/A [range] | Runtime A → B ms | Text A → B |',
'|---|---:|---:|---:|---:|---:|']
for name,w in d['workloads'].items():
 c=w['compiler'];r=w['runtime'];p=c['paired_b_over_a'];o=w['outputs']
 lines.append('| %s | %.2f → %.2f | %d → %d | %.3f [%.3f–%.3f] | %.2f → %.2f | %d → %d |'%(name,c['0']['median_wall_s']*1000,c['1']['median_wall_s']*1000,c['0']['peak_rss_kib'],c['1']['peak_rss_kib'],statistics.median(p),min(p),max(p),r['0']['median_wall_s']*1000,r['1']['median_wall_s']*1000,o[0]['text_bytes'],o[1]['text_bytes']))
lines+=['','## Longer repeats and acceptance','']
for name,w in repeat['workloads'].items():
 c=w['compiler'];r=w['runtime'];phase=c if name.startswith('auto') else r
 lines.append('- **%s:** %s medians %.2f → %.2f ms; eight paired B/A ratios %s. Compiler peak RSS %d → %d KiB.'%(name,'compiler' if name.startswith('auto') else 'runtime',phase['0']['median_wall_s']*1000,phase['1']['median_wall_s']*1000,', '.join('%.3f'%x for x in phase['paired_b_over_a']),c['0']['peak_rss_kib'],c['1']['peak_rss_kib']))
lines+=['',
'The pre-seal template observations had A/A 0.728–0.889 s and a 1.233 paired outlier; a repeat measured +0.6% median difference. Those observations are retained below. The sealed run had A/A 1.393–1.738 s, and substantially slower absolute times across both lanes, with mixed paired outliers. No frontend speedup is claimed. Unchanged runtime inputs retain identical native text: their differing timings, including the noisy member-call case, do not identify a generated-code regression. All paired results and spread remain visible.','',
'Two-base deletion removes the extra complete-destructor call on the normal path. The preserved pre-seal repeat showed about 4% improvement, but the sealed repeat does not establish a repeatable speedup: its eight paired ratios span **0.805–1.164**, median **1.0004**. Unpaired medians rise **501.14→571.08 ms**, while A/A ranges **665.95–904.43 ms** and both lanes range widely. No runtime benefit is claimed from these observations. Native text grows **1266→1412 bytes** (+146 bytes). This is required by the small O0 lifecycle comparison shape, with a fixed **two nontrivial action** expansion limit; it is not an optional transform accepted on a speed claim. Source bodies are not cloned; larger suffixes call the complete entry once. Consequently expansion is at most five subobject-call sites across normal/cleanup paths and four deallocation sites, independent of total class width. There is no iterative optimizer or unbounded inlining/growth policy.','',
'The sealed template repeat also varies widely: A spans **1.317–3.509 s**, B **1.115–3.480 s**, with paired ratios **0.905–1.153**, median **0.986**. Its unpaired median increase is **17.8%**; the paired observations do not establish a frontend regression or gain. Three-base deletion retains byte-identical native text, yet its unpaired runtime median rises **8.7%**, confirming substantial execution noise. These uncertainty limits are retained rather than treated as optimization evidence.','',
'Compiler `.text` grows **2,308,614→2,313,478 bytes** (+4,864 bytes) for required table/lifecycle behavior. The largest peak-RSS increase in the sealed comparisons is **224 KiB**. The added layout field is one 64-bit group address point per view; references/definitions use existing typed identities and bounded-lifetime storage. No unrelated cache is invalidated.','',
'## Work and stage scope','',
'- **128→512 lifecycle specializations:** 1,280→5,120 slot-work visits, 256→1,024 destruction actions, 384→1,536 defined tables, 79,872→319,488 bytes of class/view storage and 12,290→49,154 LowIR instructions. Work follows demanded facts and output.','- **4→16→64 destructor bases:** 32→128→512 slot-work visits and 344→1,234→4,834 LowIR instructions. Text is unchanged from entry on these larger-width cases (2,090 / 7,032 / 28,287 bytes). Their shared suffix path remains linear; the two-action change does not reintroduce quadratic cleanup expansion.','- Key-owned groups and declarations are emitted once. The controls check both TU publication orders and expose external references separately from local definitions in telemetry. External-table correctness is not presented as an A/B optimization against the previously incorrect ownership behavior.','',
'Spec §9’s **PA23/O0 stage-scoped acceptance** applies. Inherited +15% latency, +16 MiB RSS and 5.5× scaling diagnostics remain self-selected targets, not mandated exit gates; this preserves their prior reclassification and all handoff-121 observations. Correctness, comparison coverage, bounded work and growth remain mandatory. Later native optimization, debug and self-host performance stay with their owning stages. Acceptance here rests on required O0 representation, bounded work and documented storage/text costs. No optional optimization or speed claim is accepted on the noisy observations; unresolved timing uncertainty remains visible for review.','']
lines += ['## Preserved pre-seal observations','', '[Before entry-identity correction](../student.tests/pa23/performance122-before-entry-identity.json), [its longer repeats](../student.tests/pa23/performance122-repeat-before-entry-identity.json), and [before alias deduplication](../student.tests/pa23/performance122-before-alias-identity.json) retain every earlier sample and binary hash. Their original binary paths remain frozen; they are not relabeled as final. All workloads were rerun against the sealed `a04a8cae` binary.','']
(ROOT/'pa23/performance122.md').write_text('\n'.join(lines))
