#pragma once
#include "semantic/type_query.h"
#include "semantic/expression_store.h"
#include "semantic/fact_store.h"
#include "semantic/template_binding.h"
#include "semantic/model.h"
#include "syntax/parser.h"

namespace cppgm { namespace semantic {
// Semantic facts extend the parser's sole graph, indexed by its stable NodeId.
// The parser calls this boundary before proceeding to the next source region.
class Analyzer : public syntax::DeclarationConsumer {
public:
    Analyzer(syntax::Ast& ast, IdentifierTable& ids, bool calls = false, bool definitions = false);
    void consume(NodeId declaration) override;
    void finish();
    void require_body_facts(EntityId e) const;
    void write(std::ostream& out) const;
    void write_semantics(std::ostream& out, NodeId root) const;
    void telemetry(std::ostream& out) const;
    Types types;
    std::vector<Entity> entities;
    std::vector<Scope> scopes;
    std::vector<Declaration> declarations;
    FactStore facts;
    LiteralCallKind literal_call_kind(NodeId n) const { auto k = literal_call_kinds.get(n); return k ? LiteralCallKind(k-1) : LiteralCallKind::String; }
    Expression expression_fact(NodeId n) const { return expressions[n]; }
    NodeId call_argument(const Expression& call, unsigned i = 0) const;
    ObjectUse object_fact(NodeId n) const {
        auto use = object_uses[expressions[n].object_use];
        return use.source_owned ? project_object_use(use,n) : use;
    }
    ObjectUse project_object_use(ObjectUse use, NodeId n) const;
    std::vector<ArrowStep> arrow_steps;
    std::vector<ArrowChain> arrow_chains = std::vector<ArrowChain>(1);
    const Conversion& conversion_fact(std::uint32_t n) const { return conversions[n]; }
    EntityId specialization_pattern(EntityId e) const { return specializations[entities[e].specialization].pattern; }
    TypeArguments specialization_arguments(EntityId e) const { return argument_packs[specializations[entities[e].specialization].arguments]; }
    ArgumentId template_argument(std::uint32_t n) const { return argument_types[n]; }
    bool argument_pack(ArgumentId a) const { return !value_argument(a) && types[a].kind == TypeKind::ArgumentPack; }
    TypeArguments pack_arguments(ArgumentId a) const { return argument_packs[types[a].bound]; }
    TypeId argument_type(ArgumentId a) { return value_argument(a) ? query_fact(argument_query(a)).expression.type : a; }
    unsigned template_ordinal(EntityId e) const { return parameter_ordinals.get(e)-1; }
    const TypeQuery& type_query(QueryId id) const { return type_queries[id]; }
    QueryId type_query_child(QueryId id, unsigned i) const { return query_edges[type_queries[id].offset+i]; }
    TypeArguments query_arguments(std::uint32_t pack) const { return argument_packs[pack]; }
    ScopeId global = 0;
    std::vector<NodeId> call_arguments, default_arguments;
    NodeId default_argument(EntityId e, unsigned parameter, Conversion* converted = 0, DefaultReason reason = DefaultReason::Argument);
    NodeId default_argument_value(EntityId e, unsigned parameter) const;
    // Queries completed expression facts; keys are the expression and target.
    StaticValue static_value(NodeId n, TypeId target);
    StaticValue constant_static_value(Constant value);
    bool local_static(EntityId e) const;
    bool constant_initializer(NodeId n, TypeId target, bool local = false);
    bool constant_plan(std::uint32_t plan, bool local = false);
    bool static_initialization(EntityId e);
    std::size_t static_requests = 0, static_hits = 0;
    long double floating_value(Constant value) const;
    Constant constant_fact(NodeId n) const { return facts[n].value ? constants[facts[n].value] : Constant(); }
    std::uint64_t object_size(TypeId t) { return size(t); }
    std::uint64_t object_alignment(TypeId t) { return size(t, true); }
    bool unsigned_type(TypeId t) const { return is_unsigned(t); }
    TypeId call_type(EntityId e) const;
    bool member_demanded(EntityId e) const;
    bool dormant_hidden_friend(EntityId e) const { return entities[e].emission == Entity::HiddenFriend; }
    const VirtualClass& virtual_class(EntityId e) const { return virtual_classes[class_facts[entities[e].class_info].virtual_info]; }
    std::uint32_t virtual_class_id(EntityId e) const { return class_facts[entities[e].class_info].virtual_info; }
    std::size_t virtual_class_count() const { return virtual_classes.size(); }
    std::size_t class_count() const { return class_facts.size(); }
    std::size_t member_count() const { return members.size(); }
    const std::vector<EntityId>& demanded_vtables() const { return vtable_emission; }
    EntityId local_function(EntityId e) const { return entities[e].class_info ? class_facts[entities[e].class_info].local_function : local_enum_functions.get(e); }
    unsigned local_ordinal(EntityId e) const { return entities[e].class_info ? class_facts[entities[e].class_info].local_ordinal : local_enum_ordinals.get(e); }
    bool polymorphic(EntityId e) const { return entities[e].class_info && class_facts[entities[e].class_info].virtual_info; }
    std::uint64_t base_offset(TypeId t, TypeId base = 0) { size(t); return base ? base_adjustments[base_steps(t,types[base].entity)].total : class_facts[entities[types[t].entity].class_info].base_offset; }
    std::vector<BaseAdjustment> base_adjustments = std::vector<BaseAdjustment>(1);
    Index base_adjustment_index;
    std::size_t base_adjustment_work = 0, base_adjustment_hits = 0;
    EntityId direct_base(EntityId e) const { auto b = class_facts[entities[e].class_info].first_base; return b ? bases[b].base : 0; }
    bool constructor_member(EntityId e) const;
    bool constructor_needed(EntityId e);
    bool destructor_needed(EntityId e);
    bool temporary_cleanup(EntityId object);
    Expression member_pointer_expression(NodeId n, ScopeId s);
    bool trivial_destructor(TypeId t);
    EntityId type_destructor(TypeId t) const;
    EntityId converted_temporary(const Conversion& c) const;
    EntityId bound_temporary(NodeId n) const;
    bool destructor_member(EntityId e) const;
    bool function_nonthrowing(EntityId e);
    bool scalar_transfer_source(EntityId transfer, NodeId source) const;
    EntityId object_destructor(EntityId e) const { return object_destructors.get(e); }
    const LifetimeUse& lifetime_use(NodeId n) const { return lifetime_uses[lifetime_index.get(n)]; }
    std::uint32_t object_lifetime(EntityId e) const { return object_lifetimes.get(e); }
    unsigned return_count(std::uint32_t state, NodeId context) const { return return_counts.get(key(state, context)); }
    std::vector<LifetimeState> lifetimes = std::vector<LifetimeState>(1);
    std::vector<DestructionAction> destruction_actions;
    EntityId value_constructor(TypeId t) const;
    EntityId object_constructor(EntityId e) const;
    EntityId static_vptr(EntityId e) const { return static_vptr_objects.get(e); }
    const MemberFacts& member_fact(EntityId e) const { return members[entities[e].member_info]; }
    std::vector<SubobjectAction> subobject_actions;
    std::vector<InheritedArgument> inherited_arguments = std::vector<InheritedArgument>(1);
    bool synthetic_member(EntityId e) const;
    bool transfer_member(EntityId e) const;
    bool trivial_transfer(EntityId e) const;
    bool direct_transfer(EntityId e) const;
    bool class_value(TypeId t) const;
    bool indirect_value(TypeId t) const;
    bool indirect_parameter(TypeId t) const;
    const ScalarConsumption& scalar_consumption(EntityId object) const;
    bool empty_class(TypeId t) const;
    bool parameter_cleanup(EntityId e) const;
    EntityId reference_temporary(EntityId e) const { return reference_temporaries.get(e); }
    struct ReferenceAlternative { EntityId object; std::uint32_t next; };
    std::vector<ReferenceAlternative> reference_alternatives = std::vector<ReferenceAlternative>(1);
    std::uint32_t reference_choices(EntityId e) const { return conditional_references.get(e); }
    const ReferenceStorage& static_temporary(EntityId e) const { return reference_storage[static_temporaries.get(e)]; }
    EntityId reference_scalar(EntityId e) const { return reference_scalars.get(e); }
    EntityId retained_scalar(NodeId n, TypeId t) const { return retained_scalar_bindings.get(key(n,t)); }
    std::vector<ReferenceStorage> reference_storage = std::vector<ReferenceStorage>(1);
    const ValueInitialization& class_initialization(NodeId n, TypeId t) const;
    const ValueReturn& class_return(NodeId n) const;
    EntityId return_object(EntityId e) const;
    std::vector<TransferAction> transfers;
    bool nonstatic_field(EntityId e) const;
    EntityId injected_storage(EntityId field) const;
    EntityId anonymous_object(NodeId declaration) const { return anonymous_objects.get(declaration); }
    const FieldFacts& field_fact(EntityId e) const { return field_facts[field_index.get(e)]; }
    std::vector<InitAction> initializers = std::vector<InitAction>(1);
    std::vector<ListPlan> list_plans = std::vector<ListPlan>(1);
    std::vector<ListObject> list_objects = std::vector<ListObject>(1);
    std::uint32_t initializer_plan(NodeId n, TypeId t) const;
    bool zero_value(TypeId t);
    std::uint32_t prepare_zero_initialization(TypeId t);
    std::uint32_t zero_initialization(TypeId t) const { return zero_initialization_index.get(t); }
    std::vector<ZeroInitialization> zero_initializations = std::vector<ZeroInitialization>(1);
    std::vector<ZeroPart> zero_parts;
    bool empty_value(TypeId t);
    bool initializer_work(std::uint32_t plan);
    std::uint32_t constant_array_plan(EntityId e) const { return constant_arrays.get(e); }
    std::vector<ConversionObject> conversion_objects = std::vector<ConversionObject>(1);
    std::vector<UserConversion> user_conversions = std::vector<UserConversion>(1);
    IdentifierId literal_suffix(EntityId e) const { return literal_functions.get(e); }
    const PlacementNew& placement_fact(NodeId n) const { return placements[placement_index.get(n)]; }
    const DeleteExpression& delete_fact(NodeId n) const { return deletions[delete_index.get(n)]; }
    const ConstantObject& constant_construction(NodeId n, TypeId t);
    const ConstantObject& constant_value_data(Constant value);
    std::vector<ConstantField> constant_fields;
    struct Closure {
        EntityId entity = 0, function = 0, enclosing = 0, conversion = 0, thunk = 0;
        NodeId source = 0, inferred_return = 0;
        TypeId signature = 0;
        unsigned ordinal = 0;
    };
    const Closure& closure(EntityId e) const { return closures[closure_entities.get(e)]; }
    const Closure& closure_adapter(EntityId e) const { return closures[closure_adapters.get(e)]; }
private:
    FactState completion_state = FactState::NotStarted;
    Index list_index, direct_list_index, empty_list_index, empty_direct_list_index;
    Index class_typedef_declarations;
    std::vector<ListField> list_fields;
    Conversion list_initialization(NodeId n, TypeId to, ScopeId s = 0, bool direct = false);
    Conversion list_element(NodeId& cursor, TypeId to, ScopeId s);
    std::uint32_t list_aggregate(NodeId& cursor, TypeId to, ScopeId s);
    Conversion query_list_conversion(QueryId list, TypeId to, bool direct = false);
    TypeQueryFact query_list_initialization(QueryId id);
    std::uint32_t query_list_aggregate(const std::vector<QueryId>& args, unsigned& cursor, TypeId to, ScopeId scope);
    void store_query_arguments(Expression& call, const std::vector<QueryId>& args, const std::vector<Conversion>& chosen);
    bool valid_query_list(std::uint32_t plan);
    bool validate_query_list(std::uint32_t plan);
    Constant constant_query_list(std::uint32_t plan);
    void prepare_list(NodeId n, Conversion& c);
    void store_call(Expression& owner, const std::vector<NodeId>& args, const std::vector<Conversion>& selected);
    EntityId global_allocation(ETokenType op, bool array);
    bool array_operator(NodeId name) const;
    Expression delete_expression(NodeId n, ScopeId s);
    void finish_allocations();
    EntityId select_deallocation(TypeId t, bool array, bool global, ScopeId s);
    Index delete_index;
    std::vector<DeleteExpression> deletions = std::vector<DeleteExpression>(1);
    void prepare_value_boundary(TypeId t);
    void prepare_function_boundaries();
    bool local_scalar(EntityId object) const;
    bool private_scalar(EntityId object) const;
    void observe_scalar(NodeId expression);
    bool direct_class_call(NodeId expression);
    unsigned char scalar_truth(NodeId expression);
    void prepare_scalar_consumption(EntityId object);
    void schedule_parameter_bodies(EntityId& cursor);
    void query_parameter_representation(TypeId type);
    void finish_parameter_representation(TypeId type);
    void class_result(NodeId n, Expression& result, ScopeId s);
    bool record_class_initialization(NodeId n, TypeId target, NodeId source, const Conversion* selected = 0);
    void record_class_return(NodeId n, ScopeId s);
    void finish_class_returns(EntityId e);
    EntityId current_function = 0;
    unsigned body_evaluation_depth = 0;
    struct DeferredFunctionUse { EntityId target = 0; std::uint32_t next = 0; bool direct = false, queued = false, processed = false; };
    std::vector<DeferredFunctionUse> deferred_function_uses = std::vector<DeferredFunctionUse>(1);
    Index deferred_function_use_index, deferred_function_use_heads;
    std::vector<std::uint32_t> deferred_function_use_queue;
    std::size_t deferred_function_use_cursor = 0;
    void record_deferred_function_use(EntityId target);
    void activate_deferred_function_uses(EntityId owner);
    bool literal_type(TypeId type);
    bool constexpr_constructor(EntityId function);
    void check_constexpr_signature(EntityId function);
    void check_constexpr_constructor(EntityId function);
    void check_constexpr_class(EntityId cls);
    TypeId constexpr_member_type(TypeId type, NodeId specs, NodeId source, NodeId declarator, ScopeId owner);
    Index literal_type_facts, constexpr_constructor_facts, constexpr_signature_facts, constexpr_declarations;
    std::size_t constexpr_validity_work = 0;
    Index class_initializer_index, class_return_index, function_return_index;
    Index reference_temporaries;
    Index conditional_references;
    std::uint64_t reference_binding_work = 0;
    NodeId reference_operand(NodeId n) const;
    void local_reference(NodeId n, EntityId reference, bool conditional = false);
    Index static_temporaries, reference_scalars;
    Index retained_scalar_bindings;
    void static_reference(EntityId e);
    void retain_initializer_references(EntityId e);
    void retain_reference_object(NodeId n, EntityId reference, bool conditional);
    std::vector<ValueInitialization> value_initializations = std::vector<ValueInitialization>(1);
    std::vector<ValueReturn> value_returns = std::vector<ValueReturn>(1);
    std::vector<FunctionReturn> function_returns = std::vector<FunctionReturn>(1);
    void classify_transfer(EntityId e, NodeId special, ScopeId context);
    void ensure_transfers(TypeId t, bool assignment);
    void prepare_transfer(EntityId e);
    bool copy_storage_type(TypeId t);
    bool deleted_transfer(EntityId e);
    EntityId select_transfer(TypeId target, TypeId source, ValueCategory category, bool assignment,
        InitializationMode mode = InitializationMode::Direct);
    Conversion transfer_initialization(Expression value, TypeId target, InitializationMode mode);
    Conversion transfer_conversion(TypeId from, ValueCategory category, TypeId to);
    bool transfer_accessible(EntityId e, ScopeId context) const;
    void prepare_scalar_transfer(EntityId e);
    bool scalar_transfer_node(NodeId n);
    std::vector<unsigned char> scalar_transfer_nodes;
    std::uint64_t scalar_transfer_work = 0;
    Index anonymous_objects;
    Index constant_constructors, constant_objects, constant_value_objects;
    Index static_vptr_objects;
    void prepare_static_vptrs();
    std::vector<ConstantObject> constructor_constants = std::vector<ConstantObject>(1), object_constants = std::vector<ConstantObject>(1);
    std::vector<ConstructorConstantAction> constructor_constant_actions;
    std::uint32_t constant_constructor(EntityId ctor);
    std::vector<PlacementNew> placements = std::vector<PlacementNew>(1);
    Index placement_index;
    Expression placement_new(NodeId n, ScopeId s);
    Index literal_functions, literal_names, literal_call_kinds;
    IdentifierId literal_name(IdentifierId suffix);
    Expression literal_call(NodeId n, ScopeId s);
    Expression numeric_literal_call(NodeId n, ScopeId s);
    Constant literal_element(std::uint32_t literal, Constant index);
    Index initializer_work_index;
    Index initializer_index, zero_value_index, value_contexts;
    Index constant_arrays, constant_array_plans;
    Index static_initialization_facts, static_plan_facts;
    std::size_t static_initialization_work = 0, static_plan_work = 0;
    struct ConstantArrayIndex { std::uint32_t first = 0, count = 0; };
    Index constant_array_indices;
    std::vector<ConstantArrayIndex> constant_array_ranges = std::vector<ConstantArrayIndex>(1);
    std::vector<std::uint32_t> constant_array_children;
    std::uint32_t constant_array_child(std::uint32_t plan, Constant index);
    std::uint32_t constant_array_projection(NodeId source, ScopeId scope);
    Constant constant_array_element(std::uint32_t plan, Constant index);
    std::size_t constant_array_work = 0;
    void prepare_constant_array(EntityId e, bool required);
    bool constant_expression_plan(std::uint32_t plan);
    Index constant_expression_plans;
    bool constant_array_plan_valid(std::uint32_t plan);
    Index zero_initialization_index;
    TypeId initialized_field_type(TypeId owner, EntityId field);
    void aggregate_initialization(NodeId n, TypeId t, ScopeId s);
    std::uint32_t initializer_item(NodeId& cursor, TypeId t, ScopeId s);
    bool aggregate_type(TypeId t) const;
    bool string_initialization(NodeId n, TypeId t) const;
    bool string_array_type(EFundamentalType from, TypeId t) const;
    void list_conversion(NodeId n, TypeId t);
    void list_conversion_from(NodeId n, TypeId from, TypeId target, const Conversion* selected = 0);
    bool narrowing_conversion(TypeId from, TypeId target, Constant value);
    bool narrowing_needs_value(TypeId from, TypeId target);
    Index scalar_observations, scalar_consumption_index;
    std::vector<ScalarConsumption> scalar_consumptions = std::vector<ScalarConsumption>(1);
    std::uint64_t scalar_consumption_work = 0, scalar_observation_count = 0;
    std::uint64_t unit_transfer_fields = 0;
    std::uint64_t parameter_queries = 0, parameter_query_work = 0;
    Index field_index, local_class_names, local_enum_functions, local_enum_ordinals;
    std::vector<Closure> closures = std::vector<Closure>(1);
    Index closure_entities, closure_functions, closure_occurrences, closure_adapters;
    Expression lambda_expression(NodeId n, ScopeId s);
    void bind_lambda_body(NodeId n, ScopeId s);
    void finish_closures();
    EntityId placeholder_parameter = 0;
    Index placeholder_objects;
    bool deducing_placeholder = false;
    TypeId deduced_object_type(NodeId specs, NodeId declarator, NodeId initializer, ScopeId scope, TypeId& deduction);
    std::vector<FieldFacts> field_facts = std::vector<FieldFacts>(1);
    std::uint64_t alignment_attributes(NodeId n, ScopeId s);
    FieldFacts& field_metadata(EntityId e);
    Constant constant_field_value(EntityId field, Constant value);
    void bit_field_properties(EntityId field, Constant count);
    void bit_field_declaration(NodeId n, ScopeId s);
    void class_layout(EntityId e);
    syntax::AstView ast;
    bool definitions;
    IdentifierTable& ids;
    bool calls;
    bool c_linkage = false;
    struct StaticFact { FactState state = FactState::NotStarted; StaticValue value; };
    Index static_index;
    std::vector<StaticFact> static_facts;
    StaticValue static_value_impl(NodeId n, TypeId target);
    void function_defaults(EntityId e, NodeId d, ScopeId s, NodeId source);
    void bind_template_defaults(NodeId d, ScopeId s, ScopeId head = 0, bool allowed = true);
    enum class TemplateClassUseKind : unsigned char { DefaultArgument, MemberInitializer };
    struct TemplateClassUse { NodeId source; ScopeId scope, head; EntityId entity; TemplateClassUseKind kind; };
    std::vector<TemplateClassUse> template_class_uses;
    ScopeId active_template_class = 0;
    std::size_t template_default_binding_work = 0, template_default_binding_queued = 0;
    Index template_initializer_bindings;
    std::size_t template_initializer_binding_work = 0, template_initializer_binding_queued = 0;
    void bind_template_initializer(EntityId entity, ScopeId scope);
    void bind_template_default_initialization(EntityId entity, ScopeId scope);
    bool check_default_constructor(EntityId constructor);
    bool default_constructor_valid(EntityId constructor);
    void check_default_destructor(EntityId destructor);
    bool default_destructor_valid(EntityId destructor);
    bool default_destruction_valid(TypeId type, ScopeId scope, bool variant = false);
    void check_default_destruction(TypeId type, ScopeId scope, bool variant = false);
    void check_pattern_destruction(EntityId cls, ScopeId scope);
    EntityId check_default_initialization(TypeId type, ScopeId scope);
    void prepare_default_call(EntityId constructor);
    Index template_default_constructors;
    std::size_t default_initialization_work = 0, default_initialization_uses = 0;
    Index block_extern_entities;
    Index template_pattern_members, template_pattern_property_states, template_pattern_open_bases;
    void bind_pattern_member(EntityId entity, NodeId declaration, NodeId declarator);
    bool pattern_class_type(TypeId type) const;
    void check_pattern_default_initialization(TypeId type, ScopeId scope, bool base = false);
    void check_template_initialization(NodeId n, TypeId target, ScopeId scope,
        InitializationMode mode = InitializationMode::Direct);
    bool check_template_initializer_item(NodeId& cursor, TypeId target, ScopeId scope);
    bool check_template_constructor(NodeId n, TypeId target, ScopeId scope, InitializationMode mode,
        const std::vector<NodeId>* operands = nullptr);
    bool reuse_template_constructor(NodeId n, TypeId target, const std::vector<NodeId>& args,
        Expression& result, ScopeId scope, EntityId& selected);
    std::uint32_t retained_initialization(NodeId n, TypeId target);
    void remember_initialization(NodeId n, Conversion conversion);
    Index template_initialization_conversions, template_initializer_calls, template_initializer_narrowing;
    std::size_t initializer_recipe_work = 0, initializer_recipe_uses = 0;
    Index template_default_bindings;
    std::uint64_t default_argument_key(EntityId e, unsigned parameter) const;
    Index default_argument_index;
    std::vector<DefaultArgumentFact> default_argument_facts = std::vector<DefaultArgumentFact>(1);
    std::vector<DefaultDependency> default_dependencies;
    std::uint32_t active_default_fact = 0;
    void record_default_dependency(DefaultDependencyKind kind, std::uint32_t target);
    void capture_default_conversion(const Conversion& c);
    void demand_default_fact(std::uint32_t id);
    std::size_t default_dependency_work = 0, default_demand_work = 0;
    Index default_environments;
    std::size_t default_environment_work = 0, default_argument_work = 0;
    ScopeId default_environment(EntityId e, ScopeId head);
    void demand_region(NodeId root);
    ExpressionStore expressions;
    std::vector<ObjectUse> object_uses = std::vector<ObjectUse>(1);
    std::uint32_t prepare_arrow(NodeId node, ScopeId scope);
    std::uint32_t prepare_arrow(Expression object, ScopeId scope, NodeId source, bool demand);
    std::uint32_t constant_arrow_value(std::uint32_t object, std::uint32_t chain);
    std::uint32_t constant_query_arrow(QueryId object, std::uint32_t chain);
    std::uint32_t constant_arrow(NodeId node, std::uint32_t chain);
    Index object_destructors, lifetime_index, object_lifetimes, return_counts;
    std::vector<LifetimeUse> lifetime_uses = std::vector<LifetimeUse>(1);
    std::vector<EntityId> jump_bodies;
    void finish_body(EntityId e);
    EntityId destructor_declaration(TypeId type);
    EntityId default_destructor(TypeId t, ScopeId s = 0, bool demand = true);
    void destructor_actions(EntityId e);
    bool implicit_destructor_nonthrowing(EntityId cls);
    bool type_destructor_nonthrowing(TypeId type);
    bool expression_nonthrowing(NodeId node);
    bool query_nonthrowing(QueryId query, bool temporary = true);
    bool conversion_nonthrowing(const Conversion& conversion);
    bool initializer_nonthrowing(std::uint32_t plan);
    bool list_nonthrowing(std::uint32_t plan);
    bool default_constructor_nonthrowing(EntityId function);
    Index expression_exception_facts, query_exception_facts, default_exception_facts, list_exception_facts, initializer_exception_facts;
    std::size_t exception_work = 0;
    void require_destructor_class(EntityId cls);
    bool variant_destruction_effects(TypeId t);
    Index variant_destruction_index;
    void register_destruction(EntityId e);
    EntityId destination_destructor(TypeId t, ScopeId s);
    void exception_specification(EntityId e, NodeId declarator, ScopeId scope);
    void demand_exception_specification(EntityId function);
    unsigned evaluate_exception_specification(EntityId function, std::uint32_t fact);
    QueryId template_exception_query(EntityId function, std::uint32_t fact);
    Index template_exception_queries;
    void check_exception_redeclaration(EntityId function, unsigned prior, unsigned current, bool destructor);
    Index exception_specification_index;
    std::vector<ExceptionSpecificationFact> exception_specifications = std::vector<ExceptionSpecificationFact>(1);
    std::vector<EntityId> declaration_exceptions;
    Index friendships, using_access, using_functions, using_template_shapes, hidden_friends;
    unsigned using_member_access(ScopeId scope, EntityId member) const;
    bool friend_declaration(NodeId n, ScopeId s);
    void demand_friend_body(EntityId e);
    void demand_function_expression(const Expression& value);
    void instantiate_friend_body(EntityId e);
    EntityId associated_lookup(IdentifierId name, const std::vector<NodeId>& args);
    EntityId associated_type_lookup(IdentifierId name, std::vector<TypeId> work);
    ScopeId access_override = 0;
    Access declaration_access(ScopeId s) const;
    bool privileged(ScopeId context, EntityId cls) const;
    bool class_derives(EntityId derived, EntityId base) const;
    std::uint32_t access_base(EntityId entity) const;
    void check_base_entity_access(EntityId from, EntityId to, ScopeId context);
    bool base_accessible(EntityId cls, EntityId target, ScopeId context);
    bool accessible(EntityId entity, ScopeId context, ScopeId naming = 0, TypeId object = 0);
    void check_access(EntityId e, ScopeId context, ScopeId naming = 0, TypeId object = 0);
    void check_base_access(TypeId from, TypeId to, ScopeId context);
    ScopeId naming_class(ScopeId s) const;
    void record_object(Expression& owner, NodeId node, TypeId type, unsigned adjustment);
    std::vector<Conversion> conversions;
    Index function_families, function_signatures, function_ref_modes;
    std::size_t expression_work = 0, candidate_work = 0, conversion_work = 0, dependence_work = 0;
    TypeId return_type = 0;
    unsigned loop_depth = 0, switch_depth = 0;
    unsigned unevaluated_depth = 0;
    struct SwitchContext { TypeId type = 0; bool has_default = false; Index labels; };
    std::vector<SwitchContext> switches;
    IdentifierId constant_builtin = 0, abort_builtin = 0, expect_builtin = 0, invoke_builtin = 0;
    Index ordinary, tags, namespaces, qualifiers, edge_index;
    std::vector<Constant> constants;
    // Floating payloads are interned separately; common constants and entity
    // records retain their compact size. Identity excludes x87 padding bytes.
    struct FloatingConstant { long double value; std::uint64_t significand; std::uint16_t exponent; std::uint32_t next; };
    std::vector<FloatingConstant> floating_constants = std::vector<FloatingConstant>(1);
    Index floating_constant_index;
    bool floating_type(TypeId type) const;
    Constant floating_constant(TypeId type, long double value);
    Constant floating_conversion(Constant value, TypeId target);
    Constant floating_binary(ETokenType op, Constant left, Constant right, bool converted);
    bool constant_truth(Constant value) const;
    struct ConstantBody {
        EntityId function = 0;
        NodeId statement = 0;
        std::uint32_t parameters = 0, count = 0;
        bool valid = false;
    };
    struct ConstantActivation {
        std::uint32_t body = 0, arguments = 0;
        std::uint32_t object = 0;
        Constant result;
        FactState state = FactState::Active;
    };
    // Mutable execution storage lives only as long as one call. Completed
    // activations retain values, never their local environments.
    struct ConstantFrame {
        Index bindings;
        Index addresses;
        std::vector<std::uint32_t> storage;
        std::vector<EntityId> locals;
        std::vector<Constant> values = std::vector<Constant>(1);
    };
    ConstantFrame* constant_frame = 0;
    // Immutable aggregate payloads share typed child ranges. Storage identity
    // is separate: copies share values, never addresses or lifetimes.
    struct EvaluatedPart { std::uint64_t selector = 0, count = 1; Constant value; };
    struct EvaluatedObject { TypeId type = 0; std::uint32_t first = 0, count = 0, next = 0, addresses = 0, address_count = 0; };
    struct ConstantBuilder { Index slots; std::vector<EvaluatedPart> parts; };
    std::uint32_t constant_destination = 0;
    struct ConstantStorage { TypeId type = 0; EntityId entity = 0; NodeId literal = 0; Constant value; ConstantBuilder* builder = 0; std::uint32_t version = 0; bool live = true, readable = false; };
    struct ConstantAddress { std::uint32_t storage = 0, parent = 0, next = 0; TypeId type = 0; std::uint64_t selector = 0, offset = 0; bool located = false; };
    std::vector<EvaluatedObject> evaluated_objects = std::vector<EvaluatedObject>(1);
    std::vector<EvaluatedPart> evaluated_parts;
    std::vector<std::uint32_t> evaluated_address_parts;
    std::vector<ConstantStorage> constant_storage = std::vector<ConstantStorage>(1);
    std::vector<ConstantAddress> constant_addresses = std::vector<ConstantAddress>(1);
    Index evaluated_object_index, evaluated_part_index, constant_address_index, constant_entity_storage, constant_literal_storage;
    Index constant_declaration_state;
    std::size_t constant_object_work = 0, constant_address_work = 0;
    std::size_t constant_dependency_work = 0, constant_persistence_work = 0;
    Constant evaluated_object(TypeId type, const std::vector<EvaluatedPart>& parts);
    Constant evaluated_part(Constant object, std::uint64_t selector);
    Constant constant_initialize(NodeId node, TypeId type, ScopeId scope, EntityId constructor = 0);
    Constant constant_init_plan(std::uint32_t plan, ScopeId scope);
    Constant constant_construct(EntityId constructor, const std::vector<Constant>& arguments, bool zero = false);
    Constant constant_zero(TypeId type);
    bool constant_object_fields(Constant value, std::uint64_t offset = 0, EntityId field = 0);
    Constant constant_entity_value(EntityId entity);
    void check_constant_object(EntityId entity);
    void demand_constant_relocations(Constant value);
    std::uint32_t constant_storage_address(TypeId type, Constant value, EntityId entity = 0, NodeId literal = 0, bool readable = true);
    std::uint32_t constant_temporary_address(TypeId type, Constant value, EntityId temporary);
    Conversion explicit_builtin_conversion(Expression value, TypeId target, ETokenType op, ScopeId scope, NodeId operand = 0);
    Constant constant_construct_temporary(EntityId constructor, const std::vector<Constant>& args, bool zero, EntityId temporary);
    void refresh_constant_storage(std::uint32_t storage);
    Index query_literal_sources;
    std::uint32_t constant_subobject(std::uint32_t parent, TypeId type, std::uint64_t selector);
    std::uint64_t constant_offset(std::uint32_t address);
    std::uint32_t constant_entity_address(EntityId entity);
    std::uint32_t constant_address(NodeId node, ScopeId scope);
    std::uint32_t constant_base_address(std::uint32_t address, TypeId type);
    std::uint32_t constant_base_projection(std::uint32_t address, unsigned path);
    Constant constant_read(std::uint32_t address);
    Constant constant_indirect(Constant value);
    void constant_dependencies(Constant value, std::vector<ArgumentId>& arguments, Index& seen);
    Constant constant_pointer_binary(ETokenType op, Constant left, Constant right);
    bool constant_persistent(Constant value);
    Constant constant_call_result(NodeId node, ScopeId scope);
    enum class ConstantFlow : unsigned char { Next, Return, Break, Continue, Failure };
    struct ConstantStatement { ConstantFlow flow; Constant value; };
    Index constant_query_receivers;
    Index constant_body_index, constant_activation_index;
    std::vector<ConstantBody> constant_bodies = std::vector<ConstantBody>(1);
    std::vector<ConstantActivation> constant_activations = std::vector<ConstantActivation>(1);
    std::vector<EntityId> constant_parameters;
    std::uint32_t active_constant = 0;
    unsigned constant_depth = 0;
    bool constant_limited = false, constant_unavailable = false;
    std::size_t constant_steps = 0, constant_remaining = 0, constant_hits = 0;
    std::uint32_t constant_body(EntityId function);
    Constant execute_constant(EntityId function, const std::vector<Constant>& arguments, std::uint32_t object = 0, bool zero = false);
    Constant execute_constant_node(NodeId node, ScopeId scope);
    ConstantStatement execute_constant_statement(NodeId node, ScopeId scope);
    Constant execute_constant_condition(NodeId node, ScopeId scope);
    bool constant_local(EntityId entity, ScopeId scope);
    Constant constant_mutation(NodeId node, ScopeId scope);
    bool constant_step();
    Constant constant_call(NodeId node, ScopeId scope);
    Constant constant_query_call(QueryId query);
    Constant constant_query_conversion(QueryId source, Conversion conversion);
    std::uint32_t constant_query_object(QueryId source);
    std::uint32_t constant_node_object(NodeId source);
    Constant constant_node_conversion(NodeId source, Conversion conversion, ScopeId scope);
    std::vector<ClassFacts> class_facts;
    std::vector<MemberFacts> members;
    std::vector<BaseRelation> bases;
    std::vector<ObjectAction> actions;
    Index object_actions, specialization_index, explicit_pack_index, parameter_ordinals;
    Index template_families, template_signatures;
    std::vector<TypeId> canonical_parameters;
    Index canonical_value_parameters, canonical_template_parameters, canonical_nested_parameters;
    void declare_template_parameters(NodeId parameters, ScopeId scope, std::uint32_t source_head = 0, std::uint32_t frame = 0);
    std::uint32_t template_head_shape(EntityId entity);
    std::uint32_t template_head_shape(EntityId entity, Index& bindings, Index& cache, unsigned depth);
    bool template_compatible(EntityId parameter, EntityId argument, Index& bindings, unsigned depth = 1);
    EntityId template_entity(EntityId entity) const;
    TypeId apply_type_template(EntityId entity, const std::vector<ArgumentId>& arguments);
    TypeId specialize_alias(EntityId entity, const std::vector<ArgumentId>& arguments);
    Index alias_specializations, template_argument_sources, template_head_shapes, address_template_arguments;
    std::vector<TemplateAliasFact> alias_facts = std::vector<TemplateAliasFact>(1);

    ScopeId active_template_scope = 0;
    NodeId explicit_specialization_source = 0;
    EntityId declare_class_specialization(NodeId source, ScopeId scope);
    EntityId declare_function_specialization(NodeId name, ScopeId scope, TypeId type, ScopeId declared_owner = 0);
    void select_explicit_specialization(EntityId entity, NodeId source);
    EntityId declare_variable_template(NodeId declarator, NodeId init, TypeId type, ScopeId scope, NodeId source);
    EntityId variable_template_name(NodeId part, EntityId entity, ScopeId scope, bool initialize = true);
    EntityId specialize_variable(EntityId primary, const std::vector<TypeId>& arguments, bool initialize = true);
    Index variable_template_queries, variable_partial_heads, variable_partial_next;
    Index class_partial_heads, class_partial_next, class_partial_signatures;
    Index class_partial_ordering, function_partial_ordering;
    std::size_t function_ordering_work = 0, function_ordering_hits = 0;
    std::size_t class_ordering_work = 0, class_ordering_hits = 0;
    TypeId declare_class_partial(NodeId source, ScopeId scope, EntityId primary);
    void validate_partial_pattern(EntityId pattern);
    void select_partial_pattern(std::uint32_t specialization);
    bool match_partial_pattern(EntityId pattern, std::uint32_t arguments, std::vector<ArgumentId>& deduced);
    std::size_t explicit_selections = 0, variable_initializers = 0, variable_reuses = 0, variable_candidates = 0;
    std::vector<TemplateFunction> templates;
    std::vector<EntityId> template_parameters;
    Index template_default_types;
    Index active_candidate_substitutions;
    bool immediate_query_probe = false;
    std::size_t candidate_substitution_work = 0, candidate_substitution_cycles = 0;
    EntityId deduced_specialization(EntityId primary, std::vector<ArgumentId>& arguments);
    ArgumentId value_argument_id(QueryId query);
    ArgumentId template_argument_node(NodeId n, ScopeId scope);
    ArgumentId template_argument_node_impl(NodeId n, ScopeId scope);
    ArgumentId parameter_argument(EntityId parameter);
    ArgumentId canonical_argument(EntityId parameter, unsigned ordinal, Index& bindings, Index& cache, unsigned depth = 0);
    ArgumentId substitute_argument(ArgumentId arg, const Index& bindings, Index& cache, std::uint32_t frame = 0);
    bool dependent_argument(ArgumentId arg);
    ArgumentId convert_argument(ArgumentId arg, TypeId target);
    ArgumentId address_template_argument(QueryId query, TypeId target);
    EntityId bind_argument(ScopeId scope, EntityId parameter, ArgumentId arg);
    std::vector<TypeQuery> type_queries = std::vector<TypeQuery>(1);
    std::vector<QueryId> query_edges, query_slots;
    std::vector<std::uint64_t> query_hashes = std::vector<std::uint64_t>(1);
    std::vector<TypeQueryFact> query_facts = std::vector<TypeQueryFact>(1);
    QueryId incomplete_substitution = 0, active_type_query = 0;
    Index incomplete_specializations, incomplete_aliases;
    struct QueryPrerequisite { QueryId query = 0; std::uint32_t revision = 0; };
    std::vector<QueryPrerequisite> substitution_prerequisites = std::vector<QueryPrerequisite>(1);
    Index query_revisions;
    void retain_query_prerequisite(Index& owners, std::uint32_t owner);
    struct QueryDependency { QueryId consumer; std::uint32_t next; };
    std::vector<QueryDependency> query_dependencies = std::vector<QueryDependency>(1);
    Index query_dependency_heads, query_dependency_edges, class_query_heads, class_query_edges;
    std::size_t query_invalidations = 0;
    void record_query_dependency(QueryId source);
    void complete_query_class(EntityId entity);
    TypeQueryFact incomplete_query(TypeId type);
    Index query_sources, query_callee_sources, signature_parameters;
    std::size_t query_work = 0;
    struct QueryValue { std::uint32_t constant = 0; FactState state = FactState::NotStarted; };
    Index query_value_index, template_value_queries, template_value_dependence;
    std::vector<QueryValue> query_values = std::vector<QueryValue>(1);
    bool template_body_values = false;
    NodeId template_decltype_operand = 0;
    bool decltype_call_result(NodeId node) const;
    std::size_t query_value_work = 0, template_value_work = 0, template_value_uses = 0;
    std::uint32_t query_value(QueryId id);
    bool bind_template_size(NodeId node, ScopeId scope);
    bool reuse_template_value(NodeId node, ScopeId scope, Expression& result);
    bool fixed_layout_operand(NodeId node) const;
    void reuse_value_conversions(NodeId node, NodeId source, Expression& result);
    Index template_value_conversions;
    std::size_t value_conversion_variants = 0, value_conversion_records = 0;
    QueryId intern_query(TypeQuery query, const std::vector<QueryId>& children);
    QueryId expression_query(NodeId n, ScopeId s, bool callee = false);
    QueryId substitute_query(QueryId id, const Index& bindings, Index& cache, std::uint32_t owner = 0);
    TypeQueryFact query_fact(QueryId id);
    TypeId query_decltype(QueryId id, bool direct);
    TypeId fundamental_cast_type(ETokenType op);
    TypeId parameter_body_type(TypeId source);
    QueryId call_query(NodeId n, ScopeId s);
    QueryId new_query(NodeId n, ScopeId s);
    TypeQueryFact query_call(const TypeQuery& query, const std::vector<TypeQueryFact>& children);
    TypeId destructor_target(NodeId name, TypeId object, ScopeId scope);
    TypeQueryFact query_destructor(const TypeQuery& query, const std::vector<TypeQueryFact>& children);
    CallSelection select_call(EntityId family, const std::vector<Expression>& values,
        const std::vector<NodeId>* nodes, TypeId object, ValueCategory category,
        ScopeId naming, std::uint32_t explicit_arguments, std::vector<Conversion>& selected);
    TypeQueryFact query_operator(const TypeQuery& query, const std::vector<TypeQueryFact>& children);
    Expression conditional_value(Expression left, Expression right, std::vector<Conversion>& selected);
    TypeQueryFact query_conditional(const TypeQuery& query, const std::vector<TypeQueryFact>& children);
    TypeId dependent_decltype(NodeId n, ScopeId s);
    std::vector<TypeArguments> argument_packs;
    std::vector<ArgumentId> argument_types;
    std::vector<std::uint32_t> argument_slots;
    std::vector<Specialization> specializations;
    // A complete substitution frame and source type/query identify immutable
    // facts. Separate indexes retain the complete 32-bit ID spaces.
    Index specialization_type_cache, specialization_query_cache, substitution_binding_cache;
    Index template_declaration_sources;
    std::size_t template_declaration_work = 0, declaration_publications = 0;
    void publish_template_binding(NodeId source, EntityId concrete);
    std::size_t substitution_work = 0, substitution_hits = 0, substitution_records = 0;
    Index substitution_frame_index, template_type_contexts, substitution_frame_contexts;
    std::vector<TemplateSubstitutionFrame> substitution_frames = std::vector<TemplateSubstitutionFrame>(1);
    std::uint32_t substitution_frame(std::uint32_t specialization, std::uint32_t parameters,
        std::uint32_t count, std::uint32_t parent = 0, std::uint32_t arguments = 0);
    TypeId substitution_argument(std::uint32_t frame, EntityId parameter) const;
    ArgumentId make_argument_pack(const std::vector<ArgumentId>& args);
    std::uint32_t expansion_parameters(ArgumentId pattern);
    ArgumentId unexpanded_argument(std::uint32_t frame, EntityId parameter) const;
    std::uint32_t argument_frame(std::uint32_t parent, EntityId parameter, ArgumentId arg);
    TypeQueryFact query_new(const TypeQuery& q, const std::vector<TypeQueryFact>& children);
    Index argument_frame_index;
    std::uint32_t expansion_context(std::uint32_t frame);
    void bind_function_packs(NodeId parameters, ScopeId scope);
    void append_template_argument(NodeId node, ScopeId scope, ArgumentId arg, std::vector<ArgumentId>& out);
    std::uint32_t source_expansion_parameters(NodeId root);
    ScopeId expansion_scope(std::uint32_t frame, ScopeId parent);
    void expand_expression_list(NodeId list, ScopeId scope);
    Index source_expansion_index, expansion_scope_index, expanded_expression_lists, pack_size_entities, expansion_scope_frames;
    ScopeId expanded_scope(NodeId node, ScopeId parent);
    bool deduce_expansion(ArgumentId pattern, const std::vector<TypeId>& actual, Index& bindings, std::uint32_t prefix_frame = 0, DeductionKind kind = DeductionKind::Call);
    std::uint32_t expansion_frame(std::uint32_t parent, std::uint32_t parameters, unsigned lane);
    int expansion_count(std::uint32_t parameters, const Index& bindings, std::uint32_t frame);
    void substitute_arguments(ArgumentId arg, const Index& bindings, Index& cache, std::uint32_t frame, std::vector<ArgumentId>& out);
    Index expansion_parameter_index, expansion_frame_index, entity_pack_arguments;
    std::size_t expansion_work = 0, expansion_lanes = 0;
    void attach_template_context(std::uint32_t context, std::uint32_t frame);
    EntityId substitution_entity(std::uint32_t frame, EntityId source) const;
    EntityId substitution_binding(std::uint32_t frame, EntityId source);
    ScopeId substitution_scope(std::uint32_t frame, ScopeId source) const;
    bool pattern_scope(ScopeId scope) const;
    Index template_type_sources, template_signature_sources;
    Index injected_type_facts;
    bool template_type_probe = false;
    std::size_t template_type_work = 0, template_type_uses = 0;
    std::size_t template_signature_work = 0, template_signature_uses = 0, parameter_publications = 0;
    TypeId bind_template_type(NodeId specs, NodeId declarator, ScopeId scope);
    TypeId bind_template_special_type(NodeId d, ScopeId scope);
    TypeId reuse_template_type(NodeId node, ScopeId scope);
    std::vector<unsigned char> type_dependence;
    std::vector<EntityId> specialization_demand;
    std::size_t specialization_cursor = 0, template_bodies = 0, template_completions = 0;
    std::vector<EntityId> demand_queue;
    std::size_t demand_cursor = 0;
    unsigned anonymous_classes = 0, anonymous_enums = 0;
    double analysis_ms = 0;
    std::vector<Edge> edges;
    std::vector<ScopeId> qualified_work;
    std::vector<std::uint64_t> visited;
    std::uint64_t walk = 0;
    std::size_t lookup_work = 0, analyzed = 0, constant_work = 0;
    struct Body { NodeId node, declarator; ScopeId owner; EntityId entity; NodeId source; };
    struct DeferredDefault { EntityId function; unsigned parameter; };
    std::vector<DeferredDefault> declaration_defaults;
    std::vector<Body> bodies;
    std::vector<Body> friend_definitions;
    Index friend_definition_index, friend_definition_queued;
    std::vector<EntityId> friend_definition_demand;
    std::size_t friend_definition_cursor = 0;
    unsigned class_depth = 0;
    enum class Lookup { Ordinary, Tag, Namespace, Qualifier };
    std::uint64_t key(ScopeId s, IdentifierId n) const;
    EntityId local(ScopeId s, IdentifierId n, Lookup mode = Lookup::Ordinary) const;
    EntityId lookup(ScopeId s, IdentifierId n, Lookup mode = Lookup::Ordinary, bool qualified = false);
    EntityId imported(ScopeId s, IdentifierId n, Lookup mode, std::uint64_t visit);
    EntityId merge_lookup(EntityId a, EntityId b);
    bool function_binding(EntityId e) const;
    std::vector<EntityId> candidates(EntityId e);
    EntityId declare_function(ScopeId owner, IdentifierId name, NodeId source, TypeId type, bool constructor = false, TypeId conversion = 0);
    EntityId declare_alias(ScopeId s, IdentifierId name, NodeId source, TypeId type);
    TypeId source_type(EntityId e) const;
    ScopeId current_instantiation_scope(TypeId type, ScopeId use);
    void resolve_parenthesized_declaration(NodeId declaration, ScopeId scope);
    TypeId type_name(NodeId n, ScopeId s, NodeId last = 0, bool require_typename = false, bool template_name = false);
    TypeId injected_template_type(EntityId e, ScopeId use);
    TypeId qualified_type(TypeId owner, IdentifierId name, const std::vector<TypeId>& args, DependentNameKind kind);
    EntityId qualified_type_member(TypeId owner, IdentifierId name);
    Index qualified_type_members;
    EntityId resolve(NodeId name, ScopeId s, Lookup mode = Lookup::Ordinary);
    ScopeId name_owner(NodeId name, ScopeId s, bool declaration = false);
    ScopeId common_ancestor(ScopeId a, ScopeId b) const;
    ScopeId target(EntityId e) const;
    Index operator_names;
    IdentifierId terminal(NodeId name);
    IdentifierId operator_name(ETokenType op, bool array = false);
    ETokenType operator_token(NodeId name) const;
    void declare_operator(EntityId e, NodeId name);
    bool operator_expression(NodeId n, ScopeId s, ETokenType op, std::vector<NodeId> args, Expression& result, bool recipe = false);
    NodeId decl_name(NodeId d) const;
    NodeId child(NodeId n, syntax::Kind k) const;
    bool spec_has(NodeId n, ETokenType op) const;
    bool encloses(ScopeId outer, ScopeId inner) const;
    ScopeId make_scope(ScopeKind k, ScopeId parent, IdentifierId name = 0, EntityId e = 0, bool visible = true);
    void attach_scope(ScopeId s, ScopeId parent);
    EntityId make_entity(EntityKind k, ScopeId s, IdentifierId name, NodeId source);
    void bind(ScopeId s, IdentifierId n, EntityId e);
    std::uint32_t record(ScopeId s, EntityId e, NodeId source, TypeId type, EntityKind kind);
    void add_edge(ScopeId s, ScopeId to, bool is_inline = false);
    void declaration(NodeId n, ScopeId s);
    void simple(NodeId n, ScopeId s);
    unsigned base_path(TypeId from, EntityId to);
    std::uint64_t layout_base_path(unsigned path);
    unsigned base_steps(TypeId from, EntityId to);
    void record_member_receiver(Expression& result, NodeId node, TypeId object, EntityId selected, ScopeId naming, bool qualified, ScopeId context, bool layout = true);
    TypeId implicit_object_type(ScopeId s);
    void member_facts(EntityId e);
    Index injected_class_owners;
    void inject_class(ScopeId owner, ScopeId members);
    void explicit_specifier(EntityId e, NodeId source, ScopeId scope);
    bool explicit_condition_value(QueryId query);
    void virtual_declaration(EntityId e, NodeId d, NodeId init, NodeId specs, NodeId source, ScopeId s);
    void complete_virtuals(EntityId cls);
    void vtable_definition_available(EntityId e);
    void demand_vtable(EntityId cls, VtableReason reason);
    void check_covariance(EntityId e, EntityId base);
    void reject_abstract(TypeId t);
    bool abstract_value(TypeId t);
    std::vector<VirtualClass> virtual_classes = std::vector<VirtualClass>(1);
    std::vector<EntityId> key_vtable_demand, vtable_emission;
    std::size_t key_vtable_cursor = 0;
    std::size_t virtual_slot_work = 0, virtual_declaration_work = 0, virtual_demands = 0;
    Conversion object_conversion(EntityId e, TypeId object, ValueCategory category, ScopeId naming = 0);
    Expression member_value(EntityId e, unsigned object_cv, ValueCategory category);
    FunctionQualifiers function_qualifiers(NodeId parameters);
    bool prototype_scope_needed(NodeId parameters);
    void check_pointer_arithmetic(ETokenType op, TypeId left, TypeId right);
    ETokenType compound_operation(ETokenType op) const;
    void builtin_assignment_values(ETokenType op, const std::vector<Expression>& arguments, std::vector<BuiltinOperator>& results);
    void template_facts(EntityId e, ScopeId environment = 0);
    std::uint32_t retain_template_head(ScopeId environment);
    Index template_source_heads;
    Index template_lexical_frames;
    std::uint32_t template_lexical_frame(ScopeId scope);
    std::vector<Body>* template_source_deferred = 0;
    EntityId declare_template_function(ScopeId owner, IdentifierId name, NodeId source, TypeId type, bool constructor = false, bool conversion = false);
    ScopeId member_template_environment(ScopeId head, ScopeId owner);
    Index member_template_environments;
    std::uint32_t template_declaration_shape(TypeId type, ScopeId environment, TypeId* normalized = 0);
    bool equivalent_alias_template(EntityId entity, TypeId type, ScopeId environment);
    void merge_template_defaults(EntityId entity, ScopeId incoming, ScopeId previous = 0);
    Index alias_declaration_shapes;
    void instantiate_function(EntityId e);
    void instantiate_parameters(NodeId d, std::uint32_t context, std::uint32_t frame, ScopeId environment);
    EntityId deduce_target(EntityId pattern, TypeId target);
    EntityId deduce_conversion(EntityId pattern, TypeId target);
    bool template_more_specialized(EntityId a, EntityId b, unsigned arguments = ~0u, bool operator_call = false, bool conversion = false);
    NodeId instantiate_default(EntityId e, NodeId source);
    void validate_list_plan(std::uint32_t id);
    TypeId declare_class_template(NodeId n, ScopeId s, ScopeId friend_owner = 0);
    bool dependent_template_syntax(NodeId n, ScopeId s);
    EntityId specialize_class(EntityId pattern, const std::vector<TypeId>& args);
    EntityId class_template_name(NodeId part, EntityId e, ScopeId s);
    void complete_class(EntityId e);
    void class_attributes(NodeId source, ScopeId scope, EntityId entity, bool definition);
    void define_class(NodeId source, ScopeId scope, EntityId entity, ScopeId owner, bool injected, bool static_union);
    void complete_nested_class(EntityId entity);
    std::size_t nested_class_declarations = 0, nested_class_definitions = 0;
    bool template_defaults(EntityId pattern, std::vector<TypeId>& args, bool partial = false);
    ScopeId specialization_environment(EntityId e);
    std::uint32_t template_owner_shape(ScopeId scope, const std::vector<ArgumentId>& arguments);
    EntityId template_definition_pattern(EntityId primary, NodeId part, ScopeId scope);
    bool retain_template_definition(NodeId n, ScopeId s, ScopeId owner_head = 0, NodeId member_template = 0);
    void explicit_instantiation(NodeId n, ScopeId s);
    bool instantiation_suppressed(EntityId entity) const;
    bool explicit_instantiation_naming = false;
    void retain_type_access(NodeId part, TypeId qualifier, ScopeId scope);
    bool type_access_subtree(NodeId node);
    void check_substituted_type_access(NodeId node, std::uint32_t frame);
    bool substituted_type_access(NodeId node, std::uint32_t frame);
    Index template_type_access_sources, template_type_access_subtrees, template_type_access_states;
    std::vector<TemplateTypeAccess> template_type_accesses = std::vector<TemplateTypeAccess>(1);
    std::size_t template_type_access_work = 0;
    std::uint32_t definition_root(EntityId pattern);
    std::uint32_t definition_path(std::uint32_t parent, IdentifierId name);
    TemplateDefinitionOwner definition_owner(EntityId cls);
    bool instantiate_member_definition(EntityId e);
    void demand_template_storage(EntityId e);
    void demand_class_constant_storage(TypeId type);
    Index class_constant_storage;
    Index definition_roots, definition_paths, definition_index, definition_owner_index, definition_applications, storage_requested;
    Index definition_traversals, unmatched_definitions;
    Index definition_source_parameters;
    std::vector<TemplateDefinition> template_definitions = std::vector<TemplateDefinition>(1);
    std::vector<TemplateDefinitionHead> template_definition_heads = std::vector<TemplateDefinitionHead>(1);
    Index definition_source_heads;
    std::uint32_t retain_definition_head(ScopeId scope, EntityId pattern, unsigned depth);
    std::uint32_t definition_frame(const TemplateDefinition& definition, EntityId owner, ScopeId environment);
    std::vector<TemplateDefinitionOwner> definition_owners = std::vector<TemplateDefinitionOwner>(2);
    std::vector<EntityId> storage_demand;
    std::uint32_t definition_path_count = 0;
    std::size_t storage_cursor = 0;
    std::size_t template_definition_work = 0, definition_direct_work = 0;
    std::size_t definition_requests = 0, definition_hits = 0, definition_edges = 0;
    std::size_t definition_signature_requests = 0, definition_signature_work = 0;
    ScopeId member_definition_environment = 0;
    Index template_binding_index, template_pattern_entities, template_pattern_scopes, template_bound_bodies;
    Index template_base_dependence, template_class_bindings, template_pattern_bases;
    std::vector<TemplateBinding> template_bindings = std::vector<TemplateBinding>(1);
    std::size_t template_binding_work = 0;
    Index template_fixed_expressions;
    std::size_t template_fixed_work = 0, template_fixed_uses = 0;
    std::size_t template_fixed_call_work = 0, template_fixed_call_uses = 0;
    void check_fixed_expression(NodeId n, ScopeId s);
    bool reuse_fixed_expression(NodeId n, ScopeId s, Expression& result);
    bool check_fixed_call(NodeId n, ScopeId s);
    bool check_fixed_operator(NodeId n, ScopeId s);
    bool check_fixed_construction(NodeId n, ScopeId s);
    bool check_fixed_cast(NodeId n, ScopeId s, TypeId target, NodeId operand);
    void reuse_fixed_operator(NodeId n, NodeId source, ScopeId s, Expression& result);
    void reuse_fixed_construction(NodeId n, NodeId source, ScopeId s, Expression& result);
    Index template_operator_expressions;
    bool check_fixed_member(NodeId n, ScopeId s);
    bool check_template_field(NodeId n, ScopeId s, EntityId field, bool explicit_object = false);
    void bind_template_object_context(ScopeId function, NodeId parameters);
    TypeId template_method_shape(NodeId parameters, ScopeId scope);
    TemplateObjectContext template_object_context(ScopeId scope) const;
    bool reuse_template_field(NodeId n, ScopeId scope, Expression& result);
    TemplateMemberUse template_field_use(EntityId field, ScopeId scope, EntityId pattern = 0);
    Index template_object_context_index, template_field_sources, template_member_use_index;
    Index template_method_shapes;
    std::vector<unsigned char> prototype_scope_requirements;
    std::vector<NodeId> prototype_scope_work;
    Index template_class_patterns, template_class_contexts;
    std::vector<TemplateObjectContext> template_object_contexts = std::vector<TemplateObjectContext>(1);
    std::vector<TemplateMemberUse> template_member_uses = std::vector<TemplateMemberUse>(1);
    bool valid_fixed_conversion(Expression source, NodeId n, Conversion& c, ScopeId s);
    void check_fixed_conversion(Expression source, NodeId n, Conversion& c, ScopeId s);
    Conversion copy_conversion_recipe(Conversion c);
    void reuse_fixed_call(NodeId n, NodeId source, ScopeId s, Expression& result);
    void use_selected_function(EntityId e, bool direct);
    TemplateBinding bind_template_name(NodeId n, ScopeId s, NodeId last = 0);
    bool bind_template_expression(NodeId n, ScopeId s, bool callee = false);
    bool bind_template_expression_impl(NodeId n, ScopeId s, bool callee);
    EntityId pattern_declaration(EntityKind kind, ScopeId s, IdentifierId name, NodeId source, bool dependent);
    void bind_template_declaration(NodeId n, ScopeId s, std::vector<Body>* deferred = 0, bool defaults_allowed = true);
    void bind_template_body(const Body& body);
    void bind_template_statement(NodeId n, ScopeId s);
    ScopeId bind_template_class(NodeId n, ScopeId parent, EntityId entity = 0, std::vector<Body>* deferred = 0);
    void check_template_parameters(NodeId n, ScopeId s);
    std::size_t template_parameter_check_work = 0, template_parameter_check_reuses = 0;
    void index_template_members(NodeId n, std::uint32_t path, ScopeId s);
    TypeId template_member_signature(TypeId type, ScopeId head, EntityId primary, ScopeId owner);
    void template_signature_bindings(ScopeId scope, EntityId primary, Index& bindings);
    TypeId template_member_aliases(TypeId type, EntityId primary, Index& cache);
    ScopeId template_signature_owner(TypeId type, EntityId primary);
    std::uint32_t check_template_member_definition(NodeId d, std::uint32_t path, IdentifierId name, ScopeId head, EntityId primary);
    std::uint32_t template_signature_shape(ArgumentId argument);
    Index template_signature_shapes;
    std::size_t template_signature_shape_work = 0, template_signature_shape_hits = 0;
    QueryId template_signature_query(QueryId query, EntityId primary, Index& cache);
    int template_exception(NodeId d, ScopeId s);
    Index template_prototype_index, template_prototype_sources;
    Index template_signature_index, template_signature_groups;
    struct TemplatePrototype {
        NodeId declarator; ScopeId environment; std::uint32_t next;
        TypeId signature = 0; std::uint32_t definitions = 0;
        bool inline_definition = false;
        TemplatePrototype(NodeId d = 0, ScopeId s = 0, std::uint32_t n = 0, bool defined = false)
            : declarator(d), environment(s), next(n), inline_definition(defined) {}
    };
    std::vector<TemplatePrototype> template_prototypes = std::vector<TemplatePrototype>(1);

    std::uint32_t intern_arguments(const std::vector<TypeId>& args);
    EntityId specialize(EntityId pattern, const std::vector<TypeId>& args, bool explicit_head = false);
    bool dependent_type(TypeId type);
    TypeId substitute_type(TypeId pattern, const Index& bindings, Index& cache, std::uint32_t owner = 0);
    bool deduce_type(TypeId pattern, TypeId actual, Index& bindings, DeductionKind kind = DeductionKind::Call);
    bool deduce_sequence(const std::vector<ArgumentId>& pattern, const std::vector<ArgumentId>& actual, Index& bindings, DeductionKind kind);
    EntityId deduce_function(EntityId pattern, const std::vector<NodeId>& args, unsigned begin = 0);
    EntityId deduce_function(EntityId pattern, const std::vector<Expression>& args, unsigned begin = 0);
    template<class Arguments> EntityId deduce_function_values(EntityId pattern, const Arguments& args);
    EntityId explicit_template(NodeId name, EntityId binding, ScopeId s);
    void demand_specialization(EntityId e);
    void demand_member(EntityId e, MemberDemandReason reason = MemberDemandReason::Use);
    void require_member_definition(EntityId e);
    void require_member_body(EntityId e);
    void prepare_value_initialization(TypeId t, ScopeId s = 0);
    EntityId default_constructor(TypeId t, ScopeId s = 0, bool demand = true);
    EntityId choose_constructor(TypeId t, const std::vector<NodeId>& args, Expression* result = 0, ScopeId scope = 0,
        bool direct = true, bool probe = false, const std::vector<Expression>* values = 0);
    bool converting_transfer(EntityId constructor, const Expression& call) const;
    Conversion result_conversion(EntityId constructor, const Expression& call, TypeId target);
    void constructor_actions(EntityId e);
    bool inherit_using(NodeId name, ScopeId scope);
    void inherited_constructors(EntityId cls);
    void inherited_forwarding(EntityId e);
    bool base_initialization = false;
    bool class_initialize(NodeId n, TypeId target, ScopeId s, InitializationMode mode);
    void default_initialize(EntityId object, NodeId declarator = 0);
    bool derived_from(TypeId from, TypeId to);
    void write_function(std::ostream& out, EntityId e, NodeId body, ScopeId scope, unsigned depth, bool definition = true) const;
    void write_object(std::ostream& out, EntityId e, NodeId init, unsigned depth) const;
    void write_action(std::ostream& out, const ObjectAction& action, unsigned depth) const;
    void function_body(const Body& body);
    void check_jumps(NodeId body, bool binding_only = false);
    void schedule_body(const Body& body);
    void statements(NodeId n, ScopeId s);
    void resolve_statement(NodeId n, ScopeId s);
    void resolve_condition(NodeId n, ScopeId s, bool is_switch);
    TypeId condition_target(Expression value, bool is_switch);
    Expression template_statement_value(NodeId n, ScopeId s);
    bool fixed_initializer_operands(NodeId n) const;
    bool template_aggregate_type(TypeId target) const;
    Index template_pattern_aggregates;
    void bind_template_condition(NodeId n, ScopeId s, bool is_switch);
    void bind_template_return(NodeId n, ScopeId s);
    Index template_statement_conversions;
    std::size_t body_checks = 0, body_lifetime_checks = 0;
    std::size_t statement_conversion_work = 0, statement_conversion_uses = 0;
    Conversion return_conversion(NodeId source, Expression value, TypeId target, bool eligible);
    Expression expression(NodeId n, ScopeId s);
    Expression resolve_expression(NodeId n, ScopeId s);
    bool invoke_expression(NodeId n, ScopeId s);
    Expression callable_expression(NodeId n, ScopeId s, NodeId callee, std::vector<NodeId> args, Expression fn);
    Expression call_expression(NodeId n, ScopeId s);
    Expression unary_expression(NodeId n, ScopeId s);
    Expression binary_expression(NodeId n, ScopeId s);
    Expression cast_expression(NodeId n, ScopeId s, TypeId target, NodeId operand, bool recipe = false);
    TypeId value_type(TypeId t);
    TypeId decay(TypeId t);
    TypeId promote_expression(NodeId n);
    TypeId promote(TypeId t);
    TypeId arithmetic_type(TypeId a, TypeId b);
    TypeId composite_pointer(TypeId a, TypeId b);
    bool object_pointer(TypeId t);
    bool arithmetic(TypeId t) const;
    bool fundamental(TypeId t, EFundamentalType f) const;
    bool pointer(TypeId t) const;
    bool null_constant(NodeId n);
    bool qualification(TypeId from, TypeId to, unsigned& added, bool intermediate_const = true);
    bool similar_type(TypeId a, TypeId b);
    Conversion conversion(NodeId n, TypeId target, bool user = true);
    Conversion conversion_value(Expression source, TypeId target, bool user = true, NodeId node = 0);
    Conversion standard_conversion(Expression source, TypeId target, NodeId node = 0);
    Conversion conversion_function(NodeId n, TypeId target, bool explicit_allowed = false, bool direct_reference = false, EntityId object = 0);
    Conversion conversion_function_value(Expression source, TypeId target, bool explicit_allowed = false, bool direct_reference = false, EntityId object = 0);
    void prepare_user_conversion(NodeId n, Conversion& conversion, ConversionUse use = ConversionUse::Temporary);
    std::vector<EntityId> conversion_candidates(TypeId source);
    EntityId conversion_lookup(ScopeId owner, TypeId target, bool deduce = true);
    Index conversion_families, conversion_bindings;
    void builtin_operators(ETokenType op, const std::vector<NodeId>& arguments, std::vector<BuiltinOperator>& results);
    void builtin_operators_values(ETokenType op, const std::vector<Expression>& arguments, std::vector<BuiltinOperator>& results, const std::vector<NodeId>* nodes = 0);
    std::vector<TypeId> builtin_operand_types(NodeId n);
    std::vector<TypeId> builtin_operand_types_value(Expression source, bool modifying = false);
    Conversion converting_constructor(NodeId n, TypeId target);
    Conversion converting_constructor_value(Expression source, TypeId target, NodeId node = 0);
    void materialize_conversion(NodeId n, Conversion& c, bool defer = false,
        ConversionUse use = ConversionUse::Temporary);
    void record_call(Expression& owner, const std::vector<NodeId>& args, std::vector<Conversion>& selected);
    bool better(const Conversion* a, const Conversion* b, std::size_t count);
    Conversion ellipsis_conversion(NodeId n);
    Conversion ellipsis_conversion_value(Expression source);
    void apply_conversion(NodeId n, Conversion& c);
    void record_conversion(Expression& owner, NodeId n, Conversion c);
    Conversion boolean_conversion(NodeId n);
    Conversion boolean_conversion_value(Expression source, NodeId node = 0);
    Expression value_fact(const Expression& source) const;
    void require_conversion(NodeId n, TypeId target, bool direct = false);
    void select_function(NodeId n, EntityId e, bool direct = true);
    void initialize(NodeId init, TypeId target, ScopeId s, InitializationMode mode = InitializationMode::Direct);
    TypeId builtin_binary(ETokenType op, NodeId a, NodeId b, Expression& result);
    void modifiable(NodeId n);
    void write_resolved(std::ostream& out, NodeId n, unsigned depth) const;
    void write_expression(std::ostream& out, NodeId n, unsigned depth, TypeId override_type = 0, ValueCategory override_category = ValueCategory::Prvalue) const;
    void write_variable(std::ostream& out, NodeId d, NodeId init, unsigned depth) const;
    void write_entity_name(std::ostream& out, EntityId e) const;
    void template_declaration(NodeId n, ScopeId s);
    void namespace_declaration(NodeId n, ScopeId s);
    TypeId class_type(NodeId n, ScopeId s, IdentifierId anonymous_name = 0, bool emit = true, bool static_union = false);
    TypeId enum_type(NodeId n, ScopeId s, IdentifierId anonymous_name = 0, bool emit = true);
    TypeId specifiers(NodeId n, ScopeId s, IdentifierId anonymous_name = 0);
    TypeId type_id(NodeId n, ScopeId s);
    TypeId declarator(NodeId n, TypeId base, ScopeId s, NodeId dynamic_array = 0, bool name_resolved = false, NodeId specs = 0);
    TypeId parameter(NodeId n, ScopeId s);
    EntityId declare_object(NodeId d, NodeId init, TypeId t, NodeId specs, ScopeId s, NodeId source);
    void declaration_attributes(EntityId e, NodeId specs, NodeId source);
    Constant evaluate(NodeId n, ScopeId s);
    Constant evaluate_value(NodeId n, ScopeId s);
    Constant binary(ETokenType op, Constant a, Constant b, bool converted = false);
    Constant convert(Constant value, TypeId to, bool explicit_cast = false);
    TypeId expression_type(NodeId n, ScopeId s, bool decltype_form = false);
    std::uint64_t size(TypeId t, bool alignment = false, bool probe = false);
    bool integral(TypeId t) const;
    bool is_unsigned(TypeId t) const;
    bool scoped_enum(TypeId t) const;
    unsigned width(TypeId t) const;
    void write_scope(std::ostream& out, ScopeId s, unsigned depth) const;
    void write_type(std::ostream& out, TypeId t, NodeId display_name = 0, ETokenType key = TOK_INVALID, TypeId completed = 0) const;
    void write_name(std::ostream& out, NodeId n) const;
    void spelling(std::ostream& out, IdentifierId n) const;
};
} }
