#pragma once
#include "semantic/model.h"
#include "syntax/parser.h"

namespace cppgm { namespace semantic {
// Semantic facts extend the parser's sole graph, indexed by its stable NodeId.
// The parser calls this boundary before proceeding to the next source region.
class Analyzer : public syntax::DeclarationConsumer {
public:
    Analyzer(syntax::Ast& ast, IdentifierTable& ids, bool calls = false);
    void consume(NodeId declaration) override;
    void finish();
    void write(std::ostream& out) const;
    void write_semantics(std::ostream& out, NodeId root) const;
    void telemetry(std::ostream& out) const;
    Types types;
    std::vector<Entity> entities;
    std::vector<Scope> scopes;
    std::vector<Declaration> declarations;
    std::vector<Fact> facts;
    const Expression& expression_fact(NodeId n) const { return expressions[n]; }
    const ObjectUse& object_fact(NodeId n) const { return object_uses[expressions[n].object_use]; }
    const Conversion& conversion_fact(std::uint32_t n) const { return conversions[n]; }
    ScopeId global = 0;
    std::vector<NodeId> call_arguments, default_arguments;
    // Queries completed expression facts; keys are the expression and target.
    StaticValue static_value(NodeId n, TypeId target);
    std::size_t static_requests = 0, static_hits = 0;
    Constant constant_fact(NodeId n) const { return facts[n].value ? constants[facts[n].value] : Constant(); }
    std::uint64_t object_size(TypeId t) { return size(t); }
    std::uint64_t object_alignment(TypeId t) { return size(t, true); }
    bool unsigned_type(TypeId t) const { return is_unsigned(t); }
    TypeId call_type(EntityId e) const;
    bool member_demanded(EntityId e) const;
    bool constructor_member(EntityId e) const;
    bool constructor_needed(EntityId e);
    bool destructor_needed(EntityId e);
    bool temporary_cleanup(EntityId object);
    Expression member_pointer_expression(NodeId n, ScopeId s);
    bool trivial_destructor(TypeId t);
    EntityId type_destructor(TypeId t) const;
    EntityId converted_temporary(const Conversion& c) const;
    EntityId bound_temporary(NodeId n) const;
    bool destructor_member(EntityId e) const;
    bool function_nonthrowing(EntityId e);
    EntityId object_destructor(EntityId e) const { return object_destructors.get(e); }
    const LifetimeUse& lifetime_use(NodeId n) const { return lifetime_uses[lifetime_index.get(n)]; }
    std::uint32_t object_lifetime(EntityId e) const { return object_lifetimes.get(e); }
    unsigned return_count(std::uint32_t state, NodeId context) const { return return_counts.get(key(state, context)); }
    std::vector<LifetimeState> lifetimes = std::vector<LifetimeState>(1);
    std::vector<DestructionAction> destruction_actions;
    EntityId value_constructor(TypeId t) const;
    EntityId object_constructor(EntityId e) const;
    const MemberFacts& member_fact(EntityId e) const { return members[entities[e].member_info]; }
    std::vector<SubobjectAction> subobject_actions;
    bool synthetic_member(EntityId e) const;
    bool transfer_member(EntityId e) const;
    bool trivial_transfer(EntityId e) const;
    bool direct_transfer(EntityId e) const;
    bool class_value(TypeId t) const;
    bool indirect_value(TypeId t) const;
    bool indirect_parameter(TypeId t) const;
    bool empty_class(TypeId t) const;
    bool parameter_cleanup(EntityId e) const;
    EntityId reference_temporary(EntityId e) const { return reference_temporaries.get(e); }
    const ReferenceStorage& static_temporary(EntityId e) const { return reference_storage[static_temporaries.get(e)]; }
    EntityId reference_scalar(EntityId e) const { return reference_scalars.get(e); }
    std::vector<ReferenceStorage> reference_storage = std::vector<ReferenceStorage>(1);
    const ValueInitialization& class_initialization(NodeId n, TypeId t) const;
    const ValueReturn& class_return(NodeId n) const;
    EntityId return_object(EntityId e) const;
    std::vector<TransferAction> transfers;
    bool nonstatic_field(EntityId e) const;
    EntityId injected_storage(EntityId field) const;
    EntityId anonymous_object(NodeId declaration) const { return anonymous_objects.get(declaration); }
    const FieldFacts& field_fact(EntityId e) const { return field_facts[field_index.get(e)]; }
    std::vector<InitAction> initializers = std::vector<InitAction>(1);
    std::vector<ListPlan> list_plans = std::vector<ListPlan>(1);
    std::vector<ListObject> list_objects = std::vector<ListObject>(1);
    std::uint32_t initializer_plan(NodeId n, TypeId t) const;
    bool zero_value(TypeId t);
    std::uint32_t prepare_zero_initialization(TypeId t);
    std::uint32_t zero_initialization(TypeId t) const { return zero_initialization_index.get(t); }
    std::vector<ZeroInitialization> zero_initializations = std::vector<ZeroInitialization>(1);
    std::vector<ZeroPart> zero_parts;
    bool empty_value(TypeId t);
    bool initializer_work(std::uint32_t plan);
    std::vector<ConversionObject> conversion_objects = std::vector<ConversionObject>(1);
    std::vector<UserConversion> user_conversions = std::vector<UserConversion>(1);
    IdentifierId literal_suffix(EntityId e) const { return literal_functions.get(e); }
    const PlacementNew& placement_fact(NodeId n) const { return placements[placement_index.get(n)]; }
    const DeleteExpression& delete_fact(NodeId n) const { return deletions[delete_index.get(n)]; }
    const ConstantObject& constant_construction(NodeId n, TypeId t);
    std::vector<ConstantField> constant_fields;
private:
    Index list_index, direct_list_index, empty_list_index;
    std::vector<ListField> list_fields;
    Conversion list_initialization(NodeId n, TypeId to, ScopeId s = 0, bool direct = false);
    Conversion list_element(NodeId& cursor, TypeId to, ScopeId s);
    std::uint32_t list_aggregate(NodeId& cursor, TypeId to, ScopeId s);
    void prepare_list(NodeId n, Conversion& c);
    void store_call(Expression& owner, const std::vector<NodeId>& args, const std::vector<Conversion>& selected);
    EntityId global_allocation(ETokenType op, bool array);
    bool array_operator(NodeId name) const;
    Expression delete_expression(NodeId n, ScopeId s);
    void finish_allocations();
    EntityId select_deallocation(TypeId t, bool array, bool global, ScopeId s);
    Index delete_index;
    std::vector<DeleteExpression> deletions = std::vector<DeleteExpression>(1);
    void prepare_value_boundary(TypeId t);
    void prepare_function_boundaries();
    void class_result(NodeId n, Expression& result, ScopeId s);
    bool record_class_initialization(NodeId n, TypeId target, NodeId source, const Conversion* selected = 0);
    void record_class_return(NodeId n, ScopeId s);
    void finish_class_returns(EntityId e);
    EntityId current_function = 0;
    Index class_initializer_index, class_return_index, function_return_index;
    Index reference_temporaries;
    Index static_temporaries, reference_scalars;
    void static_reference(EntityId e);
    void retain_reference_object(NodeId n, EntityId reference, bool conditional);
    std::vector<ValueInitialization> value_initializations = std::vector<ValueInitialization>(1);
    std::vector<ValueReturn> value_returns = std::vector<ValueReturn>(1);
    std::vector<FunctionReturn> function_returns = std::vector<FunctionReturn>(1);
    void classify_transfer(EntityId e, NodeId special, ScopeId context);
    void ensure_transfers(TypeId t, bool assignment);
    void prepare_transfer(EntityId e);
    bool copy_storage_type(TypeId t);
    bool deleted_transfer(EntityId e);
    EntityId select_transfer(TypeId target, TypeId source, ValueCategory category, bool assignment);
    Conversion transfer_conversion(TypeId from, ValueCategory category, TypeId to);
    bool transfer_accessible(EntityId e, ScopeId context) const;
    Index anonymous_objects;
    Index constant_constructors, constant_objects;
    std::vector<ConstantObject> constructor_constants = std::vector<ConstantObject>(1), object_constants = std::vector<ConstantObject>(1);
    std::vector<ConstructorConstantAction> constructor_constant_actions;
    std::uint32_t constant_constructor(EntityId ctor);
    std::vector<PlacementNew> placements = std::vector<PlacementNew>(1);
    Index placement_index;
    Expression placement_new(NodeId n, ScopeId s);
    Index literal_functions, literal_names;
    IdentifierId literal_name(IdentifierId suffix);
    Expression literal_call(NodeId n, ScopeId s);
    Index initializer_work_index;
    Index initializer_index, zero_value_index, value_contexts;
    Index zero_initialization_index;
    TypeId initialized_field_type(TypeId owner, EntityId field);
    void aggregate_initialization(NodeId n, TypeId t, ScopeId s);
    std::uint32_t initializer_item(NodeId& cursor, TypeId t, ScopeId s);
    bool aggregate_type(TypeId t) const;
    bool string_initialization(NodeId n, TypeId t) const;
    void list_conversion(NodeId n, TypeId t);
    Index field_index;
    std::vector<FieldFacts> field_facts = std::vector<FieldFacts>(1);
    std::uint64_t alignment_attributes(NodeId n, ScopeId s);
    FieldFacts& field_metadata(EntityId e);
    void bit_field_declaration(NodeId n, ScopeId s);
    void class_layout(EntityId e);
    syntax::Ast& ast;
    IdentifierTable& ids;
    bool calls;
    bool c_linkage = false;
    struct StaticFact { FactState state = FactState::NotStarted; StaticValue value; };
    Index static_index;
    std::vector<StaticFact> static_facts;
    StaticValue static_value_impl(NodeId n, TypeId target);
    void function_defaults(EntityId e, NodeId d, ScopeId s);
    std::vector<Expression> expressions;
    std::vector<ObjectUse> object_uses = std::vector<ObjectUse>(1);
    Index object_destructors, lifetime_index, object_lifetimes, return_counts;
    std::vector<LifetimeUse> lifetime_uses = std::vector<LifetimeUse>(1);
    std::vector<NodeId> jump_bodies;
    EntityId default_destructor(TypeId t, ScopeId s = 0);
    void destructor_actions(EntityId e);
    bool variant_destruction_effects(TypeId t);
    Index variant_destruction_index;
    void register_destruction(EntityId e);
    void exception_specification(EntityId e, NodeId declarator, ScopeId scope);
    Index friendships, using_access, using_functions, hidden_friends;
    bool friend_declaration(NodeId n, ScopeId s);
    EntityId associated_lookup(IdentifierId name, const std::vector<NodeId>& args);
    ScopeId access_override = 0;
    Access declaration_access(ScopeId s) const;
    bool privileged(ScopeId context, EntityId cls) const;
    bool class_derives(EntityId derived, EntityId base) const;
    void check_access(EntityId e, ScopeId context, ScopeId naming = 0, TypeId object = 0);
    void check_base_access(TypeId from, TypeId to, ScopeId context);
    ScopeId naming_class(ScopeId s) const;
    void record_object(Expression& owner, NodeId node, TypeId type, unsigned adjustment);
    std::vector<Conversion> conversions;
    Index function_families, function_signatures, function_ref_modes;
    std::size_t expression_work = 0, candidate_work = 0, conversion_work = 0, dependence_work = 0;
    TypeId return_type = 0;
    unsigned loop_depth = 0, switch_depth = 0;
    unsigned unevaluated_depth = 0;
    struct SwitchContext { TypeId type = 0; bool has_default = false; Index labels; };
    std::vector<SwitchContext> switches;
    IdentifierId constant_builtin = 0, abort_builtin = 0;
    Index ordinary, tags, namespaces, qualifiers, edge_index;
    std::vector<Constant> constants;
    std::vector<ClassFacts> class_facts;
    std::vector<MemberFacts> members;
    std::vector<BaseRelation> bases;
    std::vector<ObjectAction> actions;
    Index object_actions, specialization_index;
    std::vector<TemplateFunction> templates;
    std::vector<EntityId> template_parameters;
    std::vector<TypeArguments> argument_packs;
    std::vector<TypeId> argument_types;
    std::vector<std::uint32_t> argument_slots;
    std::vector<Specialization> specializations;
    std::vector<unsigned char> type_dependence;
    std::vector<EntityId> specialization_demand;
    std::vector<EntityId> demand_queue;
    std::size_t demand_cursor = 0;
    unsigned anonymous_classes = 0, anonymous_enums = 0;
    double analysis_ms = 0;
    std::vector<Edge> edges;
    std::vector<ScopeId> qualified_work;
    std::vector<std::uint64_t> visited;
    std::uint64_t walk = 0;
    std::size_t lookup_work = 0, analyzed = 0, constant_work = 0;
    struct Body { NodeId node, declarator; ScopeId owner; EntityId entity; NodeId source; };
    std::vector<Body> bodies;
    unsigned class_depth = 0;
    enum class Lookup { Ordinary, Tag, Namespace, Qualifier };
    std::uint64_t key(ScopeId s, IdentifierId n) const;
    EntityId local(ScopeId s, IdentifierId n, Lookup mode = Lookup::Ordinary) const;
    EntityId lookup(ScopeId s, IdentifierId n, Lookup mode = Lookup::Ordinary, bool qualified = false);
    EntityId imported(ScopeId s, IdentifierId n, Lookup mode, std::uint64_t visit);
    EntityId merge_lookup(EntityId a, EntityId b);
    bool function_binding(EntityId e) const;
    std::vector<EntityId> candidates(EntityId e);
    EntityId declare_function(ScopeId owner, IdentifierId name, NodeId source, TypeId type, bool constructor = false, TypeId conversion = 0);
    EntityId declare_alias(ScopeId s, IdentifierId name, NodeId source, TypeId type);
    TypeId source_type(EntityId e) const;
    EntityId resolve(NodeId name, ScopeId s, Lookup mode = Lookup::Ordinary);
    ScopeId name_owner(NodeId name, ScopeId s, bool declaration = false);
    ScopeId common_ancestor(ScopeId a, ScopeId b) const;
    ScopeId target(EntityId e) const;
    Index operator_names;
    IdentifierId terminal(NodeId name);
    IdentifierId operator_name(ETokenType op, bool array = false);
    ETokenType operator_token(NodeId name) const;
    void declare_operator(EntityId e, NodeId name);
    bool operator_expression(NodeId n, ScopeId s, ETokenType op, std::vector<NodeId> args, Expression& result);
    NodeId decl_name(NodeId d) const;
    NodeId child(NodeId n, syntax::Kind k) const;
    bool spec_has(NodeId n, ETokenType op) const;
    bool encloses(ScopeId outer, ScopeId inner) const;
    ScopeId make_scope(ScopeKind k, ScopeId parent, IdentifierId name = 0, EntityId e = 0, bool visible = true);
    void attach_scope(ScopeId s, ScopeId parent);
    EntityId make_entity(EntityKind k, ScopeId s, IdentifierId name, NodeId source);
    void bind(ScopeId s, IdentifierId n, EntityId e);
    std::uint32_t record(ScopeId s, EntityId e, NodeId source, TypeId type, EntityKind kind);
    void add_edge(ScopeId s, ScopeId to, bool is_inline = false);
    void declaration(NodeId n, ScopeId s);
    void simple(NodeId n, ScopeId s);
    unsigned base_steps(TypeId from, EntityId to) const;
    TypeId implicit_object_type(ScopeId s);
    void member_facts(EntityId e);
    Conversion object_conversion(EntityId e, TypeId object, ValueCategory category, ScopeId naming = 0);
    void template_facts(EntityId e);
    std::uint32_t intern_arguments(const std::vector<TypeId>& args);
    EntityId specialize(EntityId pattern, const std::vector<TypeId>& args);
    bool dependent_type(TypeId type);
    TypeId substitute_type(TypeId pattern, const Index& bindings, Index& cache);
    bool deduce_type(TypeId pattern, TypeId actual, Index& bindings);
    EntityId deduce_function(EntityId pattern, const std::vector<NodeId>& args);
    EntityId explicit_template(NodeId name, EntityId binding, ScopeId s);
    void demand_specialization(EntityId e);
    void demand_member(EntityId e);
    void prepare_value_initialization(TypeId t, ScopeId s = 0);
    EntityId default_constructor(TypeId t, ScopeId s = 0, bool demand = true);
    EntityId choose_constructor(TypeId t, const std::vector<NodeId>& args, Expression* result = 0, ScopeId scope = 0, bool direct = true, bool probe = false);
    bool converting_transfer(EntityId constructor, const Expression& call) const;
    Conversion elided_conversion(const Expression& call, TypeId target);
    void constructor_actions(EntityId e);
    bool inherit_using(NodeId name, ScopeId scope);
    void inherited_constructors(EntityId cls);
    bool base_initialization = false;
    bool class_initialize(NodeId n, TypeId target, ScopeId s);
    void default_initialize(EntityId object);
    bool derived_from(TypeId from, TypeId to);
    void write_function(std::ostream& out, EntityId e, NodeId body, ScopeId scope, unsigned depth, bool definition = true) const;
    void write_object(std::ostream& out, EntityId e, NodeId init, unsigned depth) const;
    void write_action(std::ostream& out, const ObjectAction& action, unsigned depth) const;
    void function_body(const Body& body);
    void check_jumps(NodeId body);
    void schedule_body(const Body& body);
    void statements(NodeId n, ScopeId s);
    void resolve_statement(NodeId n, ScopeId s);
    void resolve_condition(NodeId n, ScopeId s, bool is_switch);
    Expression expression(NodeId n, ScopeId s);
    Expression resolve_expression(NodeId n, ScopeId s);
    Expression call_expression(NodeId n, ScopeId s);
    Expression unary_expression(NodeId n, ScopeId s);
    Expression binary_expression(NodeId n, ScopeId s);
    Expression cast_expression(NodeId n, ScopeId s, TypeId target, NodeId operand);
    TypeId value_type(TypeId t);
    TypeId decay(TypeId t);
    TypeId promote_expression(NodeId n);
    TypeId promote(TypeId t);
    TypeId arithmetic_type(TypeId a, TypeId b);
    TypeId composite_pointer(TypeId a, TypeId b);
    bool object_pointer(TypeId t);
    bool arithmetic(TypeId t) const;
    bool fundamental(TypeId t, EFundamentalType f) const;
    bool pointer(TypeId t) const;
    bool null_constant(NodeId n);
    bool qualification(TypeId from, TypeId to, unsigned& added, bool intermediate_const = true);
    bool similar_type(TypeId a, TypeId b);
    Conversion conversion(NodeId n, TypeId target, bool user = true);
    Conversion standard_conversion(Expression source, TypeId target, NodeId node = 0);
    Conversion conversion_function(NodeId n, TypeId target, bool explicit_allowed = false, bool direct_reference = false, EntityId object = 0);
    void prepare_user_conversion(NodeId n, Conversion& conversion);
    std::vector<EntityId> conversion_candidates(TypeId source);
    EntityId conversion_lookup(ScopeId owner, TypeId target);
    Index conversion_families, conversion_bindings;
    void builtin_operators(ETokenType op, const std::vector<NodeId>& arguments, std::vector<BuiltinOperator>& results);
    std::vector<TypeId> builtin_operand_types(NodeId n);
    Conversion converting_constructor(NodeId n, TypeId target);
    void materialize_conversion(NodeId n, Conversion& c, bool defer = false);
    void record_call(Expression& owner, const std::vector<NodeId>& args, std::vector<Conversion>& selected);
    bool better(const Conversion* a, const Conversion* b, std::size_t count);
    Conversion ellipsis_conversion(NodeId n);
    void apply_conversion(NodeId n, Conversion& c);
    void record_conversion(Expression& owner, NodeId n, Conversion c);
    Conversion boolean_conversion(NodeId n);
    Expression value_fact(const Expression& source) const;
    void require_conversion(NodeId n, TypeId target, bool direct = false);
    void select_function(NodeId n, EntityId e);
    void initialize(NodeId init, TypeId target, ScopeId s);
    TypeId builtin_binary(ETokenType op, NodeId a, NodeId b, Expression& result);
    void modifiable(NodeId n);
    void write_resolved(std::ostream& out, NodeId n, unsigned depth) const;
    void write_expression(std::ostream& out, NodeId n, unsigned depth, TypeId override_type = 0, ValueCategory override_category = ValueCategory::Prvalue) const;
    void write_variable(std::ostream& out, NodeId d, NodeId init, unsigned depth) const;
    void write_entity_name(std::ostream& out, EntityId e) const;
    void template_declaration(NodeId n, ScopeId s);
    void namespace_declaration(NodeId n, ScopeId s);
    TypeId class_type(NodeId n, ScopeId s, IdentifierId anonymous_name = 0, bool emit = true, bool static_union = false);
    TypeId enum_type(NodeId n, ScopeId s, IdentifierId anonymous_name = 0, bool emit = true);
    TypeId specifiers(NodeId n, ScopeId s, IdentifierId anonymous_name = 0);
    TypeId type_id(NodeId n, ScopeId s);
    TypeId declarator(NodeId n, TypeId base, ScopeId s, NodeId dynamic_array = 0);
    TypeId parameter(NodeId n, ScopeId s);
    EntityId declare_object(NodeId d, NodeId init, TypeId t, NodeId specs, ScopeId s, NodeId source);
    Constant evaluate(NodeId n, ScopeId s);
    Constant evaluate_value(NodeId n, ScopeId s);
    Constant binary(ETokenType op, Constant a, Constant b, bool converted = false);
    Constant convert(Constant value, TypeId to, bool explicit_cast = false);
    TypeId expression_type(NodeId n, ScopeId s, bool decltype_form = false);
    std::uint64_t size(TypeId t, bool alignment = false);
    bool integral(TypeId t) const;
    bool is_unsigned(TypeId t) const;
    bool scoped_enum(TypeId t) const;
    unsigned width(TypeId t) const;
    void write_scope(std::ostream& out, ScopeId s, unsigned depth) const;
    void write_type(std::ostream& out, TypeId t, NodeId display_name = 0, ETokenType key = TOK_INVALID, TypeId completed = 0) const;
    void write_name(std::ostream& out, NodeId n) const;
    void spelling(std::ostream& out, IdentifierId n) const;
};
} }
