#pragma once
#include "semantic/model.h"
#include "syntax/parser.h"

namespace cppgm { namespace semantic {
// Semantic facts extend the parser's sole graph, indexed by its stable NodeId.
// The parser calls this boundary before proceeding to the next source region.
class Analyzer : public syntax::DeclarationConsumer {
public:
    Analyzer(syntax::Ast& ast, IdentifierTable& ids, bool calls = false);
    void consume(NodeId declaration) override;
    void finish();
    void write(std::ostream& out) const;
    void write_semantics(std::ostream& out, NodeId root) const;
    void telemetry(std::ostream& out) const;
    Types types;
    std::vector<Entity> entities;
    std::vector<Scope> scopes;
    std::vector<Declaration> declarations;
    std::vector<Fact> facts;
    const Expression& expression_fact(NodeId n) const { return expressions[n]; }
    const Conversion& conversion_fact(std::uint32_t n) const { return conversions[n]; }
    ScopeId global = 0;
private:
    syntax::Ast& ast;
    IdentifierTable& ids;
    bool calls;
    std::vector<Expression> expressions;
    std::vector<Conversion> conversions;
    Index function_families, function_signatures;
    std::size_t expression_work = 0, candidate_work = 0, conversion_work = 0, dependence_work = 0;
    TypeId return_type = 0;
    unsigned loop_depth = 0, switch_depth = 0;
    unsigned unevaluated_depth = 0;
    struct SwitchContext { TypeId type = 0; bool has_default = false; Index labels; };
    std::vector<SwitchContext> switches;
    IdentifierId constant_builtin = 0, abort_builtin = 0;
    Index ordinary, tags, namespaces, qualifiers, edge_index;
    std::vector<Constant> constants;
    std::vector<ClassFacts> class_facts;
    std::vector<MemberFacts> members;
    std::vector<BaseRelation> bases;
    std::vector<ObjectAction> actions;
    Index object_actions, specialization_index;
    std::vector<TemplateFunction> templates;
    std::vector<EntityId> template_parameters;
    std::vector<TypeArguments> argument_packs;
    std::vector<TypeId> argument_types;
    std::vector<std::uint32_t> argument_slots;
    std::vector<Specialization> specializations;
    std::vector<unsigned char> type_dependence;
    std::vector<EntityId> specialization_demand;
    std::vector<EntityId> demand_queue;
    std::size_t demand_cursor = 0;
    unsigned anonymous_classes = 0, anonymous_enums = 0;
    double analysis_ms = 0;
    std::vector<Edge> edges;
    std::vector<ScopeId> qualified_work;
    std::vector<std::uint64_t> visited;
    std::uint64_t walk = 0;
    std::size_t lookup_work = 0, analyzed = 0, constant_work = 0;
    struct Body { NodeId node, declarator; ScopeId owner; EntityId entity; NodeId source; };
    std::vector<Body> bodies;
    unsigned class_depth = 0;
    enum class Lookup { Ordinary, Tag, Namespace, Qualifier };
    std::uint64_t key(ScopeId s, IdentifierId n) const;
    EntityId local(ScopeId s, IdentifierId n, Lookup mode = Lookup::Ordinary) const;
    EntityId lookup(ScopeId s, IdentifierId n, Lookup mode = Lookup::Ordinary, bool qualified = false);
    EntityId imported(ScopeId s, IdentifierId n, Lookup mode, std::uint64_t visit);
    EntityId merge_lookup(EntityId a, EntityId b);
    bool function_binding(EntityId e) const;
    std::vector<EntityId> candidates(EntityId e);
    EntityId declare_function(ScopeId owner, IdentifierId name, NodeId source, TypeId type);
    EntityId declare_alias(ScopeId s, IdentifierId name, NodeId source, TypeId type);
    TypeId source_type(EntityId e) const;
    EntityId resolve(NodeId name, ScopeId s, Lookup mode = Lookup::Ordinary);
    ScopeId name_owner(NodeId name, ScopeId s);
    ScopeId common_ancestor(ScopeId a, ScopeId b) const;
    ScopeId target(EntityId e) const;
    IdentifierId terminal(NodeId name) const;
    NodeId decl_name(NodeId d) const;
    NodeId child(NodeId n, syntax::Kind k) const;
    bool spec_has(NodeId n, ETokenType op) const;
    bool encloses(ScopeId outer, ScopeId inner) const;
    ScopeId make_scope(ScopeKind k, ScopeId parent, IdentifierId name = 0, EntityId e = 0, bool visible = true);
    void attach_scope(ScopeId s, ScopeId parent);
    EntityId make_entity(EntityKind k, ScopeId s, IdentifierId name, NodeId source);
    void bind(ScopeId s, IdentifierId n, EntityId e);
    std::uint32_t record(ScopeId s, EntityId e, NodeId source, TypeId type, EntityKind kind);
    void add_edge(ScopeId s, ScopeId to, bool is_inline = false);
    void declaration(NodeId n, ScopeId s);
    void simple(NodeId n, ScopeId s);
    void member_facts(EntityId e);
    void template_facts(EntityId e);
    std::uint32_t intern_arguments(const std::vector<TypeId>& args);
    EntityId specialize(EntityId pattern, const std::vector<TypeId>& args);
    bool dependent_type(TypeId type);
    TypeId substitute_type(TypeId pattern, const Index& bindings, Index& cache);
    bool deduce_type(TypeId pattern, TypeId actual, Index& bindings);
    EntityId deduce_function(EntityId pattern, const std::vector<NodeId>& args);
    EntityId explicit_template(NodeId name, EntityId binding, ScopeId s);
    void demand_specialization(EntityId e);
    void demand_member(EntityId e);
    void default_initialize(EntityId object);
    bool derived_from(TypeId from, TypeId to);
    void write_function(std::ostream& out, EntityId e, NodeId body, ScopeId scope, unsigned depth, bool definition = true) const;
    void write_object(std::ostream& out, EntityId e, NodeId init, unsigned depth) const;
    void write_action(std::ostream& out, const ObjectAction& action, unsigned depth) const;
    void function_body(const Body& body);
    void schedule_body(const Body& body);
    void statements(NodeId n, ScopeId s);
    void resolve_statement(NodeId n, ScopeId s);
    void resolve_condition(NodeId n, ScopeId s, bool is_switch);
    Expression expression(NodeId n, ScopeId s);
    Expression resolve_expression(NodeId n, ScopeId s);
    Expression call_expression(NodeId n, ScopeId s);
    Expression unary_expression(NodeId n, ScopeId s);
    Expression binary_expression(NodeId n, ScopeId s);
    Expression cast_expression(NodeId n, ScopeId s, TypeId target, NodeId operand);
    TypeId value_type(TypeId t);
    TypeId decay(TypeId t);
    TypeId promote(TypeId t);
    TypeId arithmetic_type(TypeId a, TypeId b);
    TypeId composite_pointer(TypeId a, TypeId b);
    bool object_pointer(TypeId t);
    bool arithmetic(TypeId t) const;
    bool fundamental(TypeId t, EFundamentalType f) const;
    bool pointer(TypeId t) const;
    bool null_constant(NodeId n);
    bool qualification(TypeId from, TypeId to, unsigned& added, bool intermediate_const = true);
    bool similar_type(TypeId a, TypeId b);
    Conversion conversion(NodeId n, TypeId target);
    bool better(const Conversion* a, const Conversion* b, std::size_t count);
    Conversion ellipsis_conversion(NodeId n);
    void apply_conversion(NodeId n, Conversion c);
    void record_conversion(Expression& owner, NodeId n, Conversion c);
    Conversion boolean_conversion(NodeId n);
    Expression value_fact(const Expression& source) const;
    void require_conversion(NodeId n, TypeId target);
    void select_function(NodeId n, EntityId e);
    void initialize(NodeId init, TypeId target, ScopeId s);
    TypeId builtin_binary(ETokenType op, NodeId a, NodeId b, Expression& result);
    void modifiable(NodeId n);
    void write_resolved(std::ostream& out, NodeId n, unsigned depth) const;
    void write_expression(std::ostream& out, NodeId n, unsigned depth, TypeId override_type = 0, ValueCategory override_category = ValueCategory::Prvalue) const;
    void write_variable(std::ostream& out, NodeId d, NodeId init, unsigned depth) const;
    void write_entity_name(std::ostream& out, EntityId e) const;
    void template_declaration(NodeId n, ScopeId s);
    void namespace_declaration(NodeId n, ScopeId s);
    TypeId class_type(NodeId n, ScopeId s, IdentifierId anonymous_name = 0, bool emit = true, bool static_union = false);
    TypeId enum_type(NodeId n, ScopeId s, IdentifierId anonymous_name = 0, bool emit = true);
    TypeId specifiers(NodeId n, ScopeId s, IdentifierId anonymous_name = 0);
    TypeId type_id(NodeId n, ScopeId s);
    TypeId declarator(NodeId n, TypeId base, ScopeId s);
    TypeId parameter(NodeId n, ScopeId s);
    EntityId declare_object(NodeId d, NodeId init, TypeId t, NodeId specs, ScopeId s, NodeId source);
    Constant evaluate(NodeId n, ScopeId s);
    Constant evaluate_value(NodeId n, ScopeId s);
    Constant binary(ETokenType op, Constant a, Constant b, bool converted = false);
    Constant convert(Constant value, TypeId to, bool explicit_cast = false);
    TypeId expression_type(NodeId n, ScopeId s, bool decltype_form = false);
    std::uint64_t size(TypeId t, bool alignment = false);
    bool integral(TypeId t) const;
    bool is_unsigned(TypeId t) const;
    bool scoped_enum(TypeId t) const;
    unsigned width(TypeId t) const;
    void write_scope(std::ostream& out, ScopeId s, unsigned depth) const;
    void write_type(std::ostream& out, TypeId t, NodeId display_name = 0, ETokenType key = TOK_INVALID, TypeId completed = 0) const;
    void write_name(std::ostream& out, NodeId n) const;
    void spelling(std::ostream& out, IdentifierId n) const;
};
} }
