#!/usr/bin/env python3
"""Frozen audit inputs, A/A calibration and six wall-time ABBA blocks.

Usage: OUT A B COMMON_INPUT_DIR STORAGE_CPP
The fixed inputs are generated by performance143.py and writer_performance144.py;
their source hashes are checked against the retained checkpoint manifests.
"""
import hashlib, json, pathlib, shutil, statistics, struct, subprocess, sys, time
out=pathlib.Path(sys.argv[1]).resolve(); out.mkdir(parents=True,exist_ok=True)
binaries=dict(zip('AB',map(lambda p:pathlib.Path(p).resolve(),sys.argv[2:4])))
common=pathlib.Path(sys.argv[4]); storage=pathlib.Path(sys.argv[5])
evidence=pathlib.Path(__file__).resolve().parent/'evidence144'
def sha(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1048576),b''):h.update(b)
    return h.hexdigest()
def run(args):
    p=subprocess.run(list(map(str,args)),capture_output=True,timeout=90)
    assert p.returncode==0,(args,p.returncode,p.stderr.decode(errors='replace'))
    return p
def text_size(p):
    data=p.read_bytes(); shoff=struct.unpack_from('<Q',data,40)[0]
    if shoff:
        return sum(int(r.split()[1]) for r in run(['size','-A',p]).stdout.decode().splitlines()
                   if r.split() and r.split()[0]=='.text')
    # The established static native image has an RX program header followed
    # directly by code; no section table. Count code, excluding ELF headers.
    phoff=struct.unpack_from('<Q',data,32)[0]; entsize,count=struct.unpack_from('<HH',data,54)
    for i in range(count):
        typ,flags,off,va,pa,filesz=struct.unpack_from('<IIQQQQ',data,phoff+i*entsize)
        if typ==1 and flags&1:return filesz-(phoff+entsize*count)
    raise AssertionError('no executable text')
known=json.loads((evidence/'common-performance.json').read_text())['inputs']
sources={name:common/(name+'.cpp') for name in known}; sources['storage']=storage
for name,p in sources.items():
    expected=known[name]['sha256'] if name!='storage' else json.loads((evidence/'writer-performance.json').read_text())['input_sha256']
    assert sha(p)==expected,(name,sha(p),expected)
    shutil.copyfile(p,out/(name+'.cpp'))
result={'binaries':{k:{'path':str(v),'sha256':sha(v)} for k,v in binaries.items()},
        'flags':['-O0','--stats'],'host_linker':run(['g++','--version']).stdout.decode(),
        'inputs':{k:sha(v) for k,v in sources.items()},'runs':[],'images':{},'summary':{}}
def save(): (out/'performance.json').write_text(json.dumps(result,indent=2)+'\n')
for surface,names in [('host_object',list(sources)),('own_link',['memory','floating','exceptions'])]:
    for name in names:
        key=surface+'/'+name; source=out/(name+'.cpp'); images={}; executables={}
        # Preserve the inherited additional final/final string baseline.
        selected={k:binaries['B'] if name=='strings' else v for k,v in binaries.items()}
        for label,binary in selected.items():
            exe=out/(surface+'-'+name+label); obj=exe.with_suffix('.o')
            args=[binary,'-O0','--stats',source,'-o',obj if surface=='host_object' else exe]
            if surface=='host_object':args.insert(1,'-c')
            run(args)
            if surface=='host_object':run(['g++',obj,'-o',exe])
            run([exe]);executables[label]=exe
            images[label]={'executable_sha256':sha(exe),'text_bytes':text_size(exe),'bytes':exe.stat().st_size,
                           'compiler_sha256':sha(binary)}
            if surface=='host_object':images[label].update(object_sha256=sha(obj),object_text_bytes=text_size(obj),object_bytes=obj.stat().st_size)
        result['images'][key]=images
        for mode in ['compile','runtime']:
            for block,order in enumerate(['AAAA']+['ABBA']*6):
                for label in order:
                    args=[selected[label],'-O0','--stats',source,'-o',out/'measure'] if mode=='compile' else [executables[label]]
                    if mode=='compile' and surface=='host_object':args.insert(1,'-c')
                    start=time.perf_counter(); p=run(['/usr/bin/time','-f','%M','-o',out/'rss',*args]); elapsed=time.perf_counter()-start
                    result['runs'].append(dict(workload=key,mode=mode,block=block,label=label,wall_s=elapsed,
                        peak_rss_kib=int((out/'rss').read_text()),phase_counters=[json.loads(s) for s in p.stderr.decode().splitlines() if s.startswith('{')]))
                    save()
            rows=[r for r in result['runs'] if r['workload']==key and r['mode']==mode]
            ratios=[statistics.mean(r['wall_s'] for r in rows if r['block']==b and r['label']=='B')/
                    statistics.mean(r['wall_s'] for r in rows if r['block']==b and r['label']=='A') for b in range(1,7)]
            aa=[r['wall_s'] for r in rows if not r['block']]
            summary={'AA_range_s':[min(aa),max(aa)],'paired_ratios':ratios,'paired_ratio_median':statistics.median(ratios),
                     'paired_ratio_range':[min(ratios),max(ratios)]}
            for label in 'AB':
                samples=[r for r in rows if r['block'] and r['label']==label]
                summary[label]={'median_s':statistics.median(r['wall_s'] for r in samples),
                    'range_s':[min(r['wall_s'] for r in samples),max(r['wall_s'] for r in samples)],
                    'peak_rss_kib':max(r['peak_rss_kib'] for r in samples)}
            result['summary'].setdefault(key,{})[mode]=summary; save()
        print(key,json.dumps(result['summary'][key]),flush=True)
assert all(sha(binaries[k])==v['sha256'] for k,v in result['binaries'].items())
