struct Forward;
union Union { int a; float b; };
enum class Enum: unsigned short { A };
struct Empty {};
struct Base { virtual ~Base() {} };
struct Derived: private Base {};
struct Final final {};
struct Abstract { virtual void f()=0; };
static_assert(__is_class(Forward),"incomplete class classification");
static_assert(!__is_class(Union),"union is not class");
static_assert(__is_union(const Union),"cv union");
static_assert(__is_enum(Enum),"enum");
static_assert(__is_same(__underlying_type(Enum),unsigned short),"underlying");
static_assert(__is_empty(Empty),"empty");
static_assert(__is_polymorphic(Derived),"polymorphic");
static_assert(__is_base_of(Base,Derived),"private base counts");
static_assert(__is_base_of(Forward,Forward),"incomplete same class");
static_assert(!__is_base_of(Union,Union),"union is not its own base");
static_assert(__is_final(Final),"final");
static_assert(__is_abstract(Abstract),"abstract");
static_assert(__has_virtual_destructor(Derived),"virtual destructor");
static_assert(__has_trivial_destructor(int),"scalar destructor");
static_assert(!__has_trivial_destructor(void),"void destructor");
static_assert(__is_trivial(int),"scalar trivial");
static_assert(!__is_trivial(int&),"reference trivial");
static_assert(__is_standard_layout(int[2]),"array layout");
template<class T> struct Classification {
    static const bool value=__is_class(T);
};
template<class T> bool classify(){return __is_class(T);}
template<class T> struct Underlying { typedef __underlying_type(T) type; };
static_assert(Classification<Empty>::value,"template class");
static_assert(!Classification<int>::value,"template scalar");
static_assert(__is_same(Underlying<Enum>::type,unsigned short),"template underlying");
struct Plain { int x; };
struct User { User() noexcept {} User(int) {} User(const User&) {} ~User(){} };
struct Deleted { Deleted()=delete; Deleted(const Deleted&)=delete; };
class Private { Private(); };
struct NoDefault { NoDefault(int){} };
struct Nontrivial { Plain field; ~Nontrivial() {} };
struct BaseData { int x; }; struct MixedData: BaseData { int y; };
struct PrivateData { int a; private: int b; };
struct FirstBase: Empty { Empty first; };
static_assert(__is_trivial(Plain),"class trivial");
static_assert(__is_trivially_copyable(Plain),"class trivially copyable");
static_assert(__is_standard_layout(Plain),"class layout");
static_assert(__is_pod(Plain),"POD");
static_assert(!__is_trivial(User),"user constructor");
static_assert(!__is_trivially_copyable(Nontrivial),"destructor matters");
static_assert(!__is_standard_layout(MixedData),"mixed inherited data");
static_assert(!__is_standard_layout(PrivateData),"mixed access");
static_assert(!__is_standard_layout(FirstBase),"first member same as base");
static_assert(__is_constructible(User),"default constructible");
static_assert(__is_nothrow_constructible(User),"nothrow default");
static_assert(__is_constructible(User,int),"converting constructor");
static_assert(!__is_nothrow_constructible(User,int),"throwing constructor");
static_assert(!__is_constructible(Deleted),"deleted constructor");
static_assert(!__is_constructible(Private),"private constructor");
static_assert(!__is_constructible(NoDefault),"no constructor");
static_assert(!__is_constructible(int*,void*),"no downcast during initialization");
static_assert(!__is_constructible(int&,int),"no lvalue ref to rvalue");
static_assert(__is_constructible(const int&,int),"const reference materialization");
static_assert(__is_constructible(int[3]),"array default");
static_assert(!__is_constructible(int[]),"incomplete array");
static_assert(!__is_constructible(Plain,int),"no parenthesized aggregate init");
static_assert(__is_assignable(int&,int),"scalar assign");
static_assert(!__is_assignable(int,int),"prvalue assign");
static_assert(!__is_assignable(const int&,int),"const assign");
static_assert(__is_nothrow_assignable(Plain&,const Plain&),"default assignment");
static_assert(__is_trivially_assignable(Plain&,const Plain&),"trivial assignment");
static_assert(__is_trivially_constructible(Plain,const Plain&),"trivial copy");
template<class T, class... A> struct Constructs { static const bool value=__is_constructible(T,A...); };
static_assert(Constructs<User,int>::value,"type pack trait");
static_assert(!Constructs<NoDefault>::value,"empty pack trait");
template<class T> struct Typeof { typedef __typeof((*(T*)0)) type; };
static_assert(__is_same(Typeof<const int>::type,const int),"typeof removes reference, preserves cv");
int main(){return classify<Empty>() && !classify<int>() ? 0:1;}
